// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/cloustone/pandas/models"
)

// GetProjectsProjectIDReader is a Reader for the GetProjectsProjectID structure.
type GetProjectsProjectIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProjectsProjectIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProjectsProjectIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetProjectsProjectIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetProjectsProjectIDOK creates a GetProjectsProjectIDOK with default headers values
func NewGetProjectsProjectIDOK() *GetProjectsProjectIDOK {
	return &GetProjectsProjectIDOK{}
}

/*GetProjectsProjectIDOK handles this case with default header values.

successful operation
*/
type GetProjectsProjectIDOK struct {
	Payload *models.Project
}

func (o *GetProjectsProjectIDOK) Error() string {
	return fmt.Sprintf("[GET /projects/{projectId}][%d] getProjectsProjectIdOK  %+v", 200, o.Payload)
}

func (o *GetProjectsProjectIDOK) GetPayload() *models.Project {
	return o.Payload
}

func (o *GetProjectsProjectIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Project)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProjectsProjectIDNotFound creates a GetProjectsProjectIDNotFound with default headers values
func NewGetProjectsProjectIDNotFound() *GetProjectsProjectIDNotFound {
	return &GetProjectsProjectIDNotFound{}
}

/*GetProjectsProjectIDNotFound handles this case with default header values.

Bad request
*/
type GetProjectsProjectIDNotFound struct {
}

func (o *GetProjectsProjectIDNotFound) Error() string {
	return fmt.Sprintf("[GET /projects/{projectId}][%d] getProjectsProjectIdNotFound ", 404)
}

func (o *GetProjectsProjectIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
