version: "3.7"
services: 

    apimachinery:
        container_name: api-container
        build: 
            context:  .
            dockerfile: cmd/apimachinery/Dockerfile
            labels: 
                - "github.com/cloustone/pandas/cmd/apimachinery"
    
    dmms:
        container_name: dmms-container
        build: 
            context:  .
            dockerfile: cmd/dmms/Dockerfile
            labels: 
                - "github.com/cloustone/pandas/cmd/dmms"

    headmast:
        container_name: headmast-container
        build: 
            context:  .
            dockerfile: cmd/headmast/Dockerfile
            labels: 
                - "github.com/cloustone/pandas/cmd/headmast"

    lbs:
        container_name: lbs-container
        build: 
            context:  .
            dockerfile: cmd/lbs/Dockerfile
            labels: 
                - "github.com/cloustone/pandas/cmd/lbs"

    pms:
        container_name: pms-container
        build: 
            context:  .
            dockerfile: cmd/pms/Dockerfile
            labels: 
                - "github.com/cloustone/pandas/cmd/pms"
        
    rulechain:
        container_name: rulechain-container
        build: 
            context:  .
            dockerfile: cmd/rulechain/Dockerfile
            labels: 
                - "github.com/cloustone/pandas/cmd/rulechain"