// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/cloustone/pandas/models"
)

// GetModelReader is a Reader for the GetModel structure.
type GetModelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetModelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetModelOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetModelNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetModelOK creates a GetModelOK with default headers values
func NewGetModelOK() *GetModelOK {
	return &GetModelOK{}
}

/*GetModelOK handles this case with default header values.

successfully operation
*/
type GetModelOK struct {
	Payload models.DeviceModel
}

func (o *GetModelOK) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}][%d] getModelOK  %+v", 200, o.Payload)
}

func (o *GetModelOK) GetPayload() models.DeviceModel {
	return o.Payload
}

func (o *GetModelOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetModelNotFound creates a GetModelNotFound with default headers values
func NewGetModelNotFound() *GetModelNotFound {
	return &GetModelNotFound{}
}

/*GetModelNotFound handles this case with default header values.

model not found
*/
type GetModelNotFound struct {
}

func (o *GetModelNotFound) Error() string {
	return fmt.Sprintf("[GET /models/{modelId}][%d] getModelNotFound ", 404)
}

func (o *GetModelNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
