// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/cloustone/pandas/models"
)

// NewUpdateModelParams creates a new UpdateModelParams object
// with the default values initialized.
func NewUpdateModelParams() *UpdateModelParams {
	var ()
	return &UpdateModelParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateModelParamsWithTimeout creates a new UpdateModelParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateModelParamsWithTimeout(timeout time.Duration) *UpdateModelParams {
	var ()
	return &UpdateModelParams{

		timeout: timeout,
	}
}

// NewUpdateModelParamsWithContext creates a new UpdateModelParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateModelParamsWithContext(ctx context.Context) *UpdateModelParams {
	var ()
	return &UpdateModelParams{

		Context: ctx,
	}
}

// NewUpdateModelParamsWithHTTPClient creates a new UpdateModelParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateModelParamsWithHTTPClient(client *http.Client) *UpdateModelParams {
	var ()
	return &UpdateModelParams{
		HTTPClient: client,
	}
}

/*UpdateModelParams contains all the parameters to send to the API endpoint
for the update model operation typically these are written to a http.Request
*/
type UpdateModelParams struct {

	/*DeviceModel*/
	DeviceModel *models.DeviceModel

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update model params
func (o *UpdateModelParams) WithTimeout(timeout time.Duration) *UpdateModelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update model params
func (o *UpdateModelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update model params
func (o *UpdateModelParams) WithContext(ctx context.Context) *UpdateModelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update model params
func (o *UpdateModelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update model params
func (o *UpdateModelParams) WithHTTPClient(client *http.Client) *UpdateModelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update model params
func (o *UpdateModelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeviceModel adds the deviceModel to the update model params
func (o *UpdateModelParams) WithDeviceModel(deviceModel *models.DeviceModel) *UpdateModelParams {
	o.SetDeviceModel(deviceModel)
	return o
}

// SetDeviceModel adds the deviceModel to the update model params
func (o *UpdateModelParams) SetDeviceModel(deviceModel *models.DeviceModel) {
	o.DeviceModel = deviceModel
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateModelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DeviceModel != nil {
		if err := r.SetBodyParam(o.DeviceModel); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
