// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dmms.proto

package grpc_dmms_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Device struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty", bson:"ID,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name" json:"name,omitempty", bson:"name,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description" json:"description,omitempty", bson:"description,omitempty"`
	Status               string               `protobuf:"bytes,5,opt,name=status" json:"status,omitempty", bson:"status,omitempty"`
	UserID               string               `protobuf:"bytes,6,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	ProjectID            string               `protobuf:"bytes,7,opt,name=projectID" json:"projectID,omitempty", bson:"projectID,omitempty"`
	ModelID              string               `protobuf:"bytes,8,opt,name=modelID" json:"modelID,omitempty", bson:"modelID,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt" json:"created_at,omitempty", bson:"created_at,omitempty"`
	LastUpdatedAt        *timestamp.Timestamp `protobuf:"bytes,10,opt,name=last_updated_at,json=lastUpdatedAt" json:"last_updated_at,omitempty", bson:"last_updated_at,omitempty"`
	DataModel            *DataModel           `protobuf:"bytes,11,opt,name=data_model,json=dataModel" json:"data_model,omitempty", bson:"data_model,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{0}
}
func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (dst *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(dst, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Device) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Device) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Device) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Device) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Device) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

func (m *Device) GetModelID() string {
	if m != nil {
		return m.ModelID
	}
	return ""
}

func (m *Device) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Device) GetLastUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdatedAt
	}
	return nil
}

func (m *Device) GetDataModel() *DataModel {
	if m != nil {
		return m.DataModel
	}
	return nil
}

type Endpoint struct {
	Path                 string            `protobuf:"bytes,1,opt,name=path" json:"path,omitempty", bson:"path,omitempty"`
	Format               string            `protobuf:"bytes,2,opt,name=format" json:"format,omitempty", bson:"format,omitempty"`
	Models               map[string]string `protobuf:"bytes,3,rep,name=models" json:"models,omitempty", bson:"models,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{1}
}
func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (dst *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(dst, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Endpoint) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Endpoint) GetModels() map[string]string {
	if m != nil {
		return m.Models
	}
	return nil
}

type DataModel struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty", bson:"name,omitempty"`
	ID                   string            `protobuf:"bytes,2,opt,name=ID" json:"ID,omitempty", bson:"ID,omitempty"`
	Domain               string            `protobuf:"bytes,3,opt,name=domain" json:"domain,omitempty", bson:"domain,omitempty"`
	DataModelFields      []*DataModelField `protobuf:"bytes,4,rep,name=data_model_fields,json=dataModelFields" json:"data_model_fields,omitempty", bson:"data_model_fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DataModel) Reset()         { *m = DataModel{} }
func (m *DataModel) String() string { return proto.CompactTextString(m) }
func (*DataModel) ProtoMessage()    {}
func (*DataModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{2}
}
func (m *DataModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataModel.Unmarshal(m, b)
}
func (m *DataModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataModel.Marshal(b, m, deterministic)
}
func (dst *DataModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataModel.Merge(dst, src)
}
func (m *DataModel) XXX_Size() int {
	return xxx_messageInfo_DataModel.Size(m)
}
func (m *DataModel) XXX_DiscardUnknown() {
	xxx_messageInfo_DataModel.DiscardUnknown(m)
}

var xxx_messageInfo_DataModel proto.InternalMessageInfo

func (m *DataModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataModel) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DataModel) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *DataModel) GetDataModelFields() []*DataModelField {
	if m != nil {
		return m.DataModelFields
	}
	return nil
}

type DataModelField struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty", bson:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty", bson:"value,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type" json:"type,omitempty", bson:"type,omitempty"`
	DefaultValue         string   `protobuf:"bytes,4,opt,name=default_value,json=defaultValue" json:"default_value,omitempty", bson:"default_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataModelField) Reset()         { *m = DataModelField{} }
func (m *DataModelField) String() string { return proto.CompactTextString(m) }
func (*DataModelField) ProtoMessage()    {}
func (*DataModelField) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{3}
}
func (m *DataModelField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataModelField.Unmarshal(m, b)
}
func (m *DataModelField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataModelField.Marshal(b, m, deterministic)
}
func (dst *DataModelField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataModelField.Merge(dst, src)
}
func (m *DataModelField) XXX_Size() int {
	return xxx_messageInfo_DataModelField.Size(m)
}
func (m *DataModelField) XXX_DiscardUnknown() {
	xxx_messageInfo_DataModelField.DiscardUnknown(m)
}

var xxx_messageInfo_DataModelField proto.InternalMessageInfo

func (m *DataModelField) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DataModelField) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *DataModelField) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DataModelField) GetDefaultValue() string {
	if m != nil {
		return m.DefaultValue
	}
	return ""
}

type DeviceModel struct {
	ID                   string               `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty", bson:"ID,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name" json:"name,omitempty", bson:"name,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description" json:"description,omitempty", bson:"description,omitempty"`
	Domain               string               `protobuf:"bytes,4,opt,name=domain" json:"domain,omitempty", bson:"domain,omitempty"`
	Version              string               `protobuf:"bytes,5,opt,name=version" json:"version,omitempty", bson:"version,omitempty"`
	Endpoints            []*Endpoint          `protobuf:"bytes,6,rep,name=endpoints" json:"endpoints,omitempty", bson:"endpoints,omitempty"`
	DataModels           []*DataModel         `protobuf:"bytes,7,rep,name=dataModels" json:"dataModels,omitempty", bson:"dataModels,omitempty"`
	IsLogical            bool                 `protobuf:"varint,8,opt,name=isLogical" json:"isLogical,omitempty", bson:"isLogical,omitempty"`
	IsCompound           bool                 `protobuf:"varint,9,opt,name=isCompound" json:"isCompound,omitempty", bson:"isCompound,omitempty"`
	ChildModels          []string             `protobuf:"bytes,10,rep,name=ChildModels" json:"ChildModels,omitempty", bson:"ChildModels,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt" json:"created_at,omitempty", bson:"created_at,omitempty"`
	LastUpdatedAt        *timestamp.Timestamp `protobuf:"bytes,12,opt,name=last_updated_at,json=lastUpdatedAt" json:"last_updated_at,omitempty", bson:"last_updated_at,omitempty"`
	UserID               string               `protobuf:"bytes,13,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	Icon                 string               `protobuf:"bytes,14,opt,name=Icon" json:"Icon,omitempty", bson:"Icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeviceModel) Reset()         { *m = DeviceModel{} }
func (m *DeviceModel) String() string { return proto.CompactTextString(m) }
func (*DeviceModel) ProtoMessage()    {}
func (*DeviceModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{4}
}
func (m *DeviceModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceModel.Unmarshal(m, b)
}
func (m *DeviceModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceModel.Marshal(b, m, deterministic)
}
func (dst *DeviceModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceModel.Merge(dst, src)
}
func (m *DeviceModel) XXX_Size() int {
	return xxx_messageInfo_DeviceModel.Size(m)
}
func (m *DeviceModel) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceModel.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceModel proto.InternalMessageInfo

func (m *DeviceModel) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DeviceModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceModel) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *DeviceModel) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *DeviceModel) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *DeviceModel) GetEndpoints() []*Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *DeviceModel) GetDataModels() []*DataModel {
	if m != nil {
		return m.DataModels
	}
	return nil
}

func (m *DeviceModel) GetIsLogical() bool {
	if m != nil {
		return m.IsLogical
	}
	return false
}

func (m *DeviceModel) GetIsCompound() bool {
	if m != nil {
		return m.IsCompound
	}
	return false
}

func (m *DeviceModel) GetChildModels() []string {
	if m != nil {
		return m.ChildModels
	}
	return nil
}

func (m *DeviceModel) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *DeviceModel) GetLastUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdatedAt
	}
	return nil
}

func (m *DeviceModel) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *DeviceModel) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

type DeviceMetrics struct {
	UserID               string           `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	DeviceID             string           `protobuf:"bytes,2,opt,name=deviceID" json:"deviceID,omitempty", bson:"deviceID,omitempty"`
	Metrics              map[string]int32 `protobuf:"bytes,3,rep,name=metrics" json:"metrics,omitempty", bson:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *DeviceMetrics) Reset()         { *m = DeviceMetrics{} }
func (m *DeviceMetrics) String() string { return proto.CompactTextString(m) }
func (*DeviceMetrics) ProtoMessage()    {}
func (*DeviceMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{5}
}
func (m *DeviceMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceMetrics.Unmarshal(m, b)
}
func (m *DeviceMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceMetrics.Marshal(b, m, deterministic)
}
func (dst *DeviceMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceMetrics.Merge(dst, src)
}
func (m *DeviceMetrics) XXX_Size() int {
	return xxx_messageInfo_DeviceMetrics.Size(m)
}
func (m *DeviceMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceMetrics proto.InternalMessageInfo

func (m *DeviceMetrics) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *DeviceMetrics) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *DeviceMetrics) GetMetrics() map[string]int32 {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type DeviceMessage struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	DeviceID             string   `protobuf:"bytes,2,opt,name=deviceID" json:"deviceID,omitempty", bson:"deviceID,omitempty"`
	Endpoint             string   `protobuf:"bytes,3,opt,name=endpoint" json:"endpoint,omitempty", bson:"endpoint,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty", bson:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceMessage) Reset()         { *m = DeviceMessage{} }
func (m *DeviceMessage) String() string { return proto.CompactTextString(m) }
func (*DeviceMessage) ProtoMessage()    {}
func (*DeviceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{6}
}
func (m *DeviceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceMessage.Unmarshal(m, b)
}
func (m *DeviceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceMessage.Marshal(b, m, deterministic)
}
func (dst *DeviceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceMessage.Merge(dst, src)
}
func (m *DeviceMessage) XXX_Size() int {
	return xxx_messageInfo_DeviceMessage.Size(m)
}
func (m *DeviceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceMessage proto.InternalMessageInfo

func (m *DeviceMessage) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *DeviceMessage) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *DeviceMessage) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *DeviceMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// Device Model apis
type CreateDeviceModelRequest struct {
	UserID               string       `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	DeviceModel          *DeviceModel `protobuf:"bytes,2,opt,name=device_model,json=deviceModel" json:"device_model,omitempty", bson:"device_model,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateDeviceModelRequest) Reset()         { *m = CreateDeviceModelRequest{} }
func (m *CreateDeviceModelRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeviceModelRequest) ProtoMessage()    {}
func (*CreateDeviceModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{7}
}
func (m *CreateDeviceModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceModelRequest.Unmarshal(m, b)
}
func (m *CreateDeviceModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceModelRequest.Marshal(b, m, deterministic)
}
func (dst *CreateDeviceModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceModelRequest.Merge(dst, src)
}
func (m *CreateDeviceModelRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceModelRequest.Size(m)
}
func (m *CreateDeviceModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceModelRequest proto.InternalMessageInfo

func (m *CreateDeviceModelRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CreateDeviceModelRequest) GetDeviceModel() *DeviceModel {
	if m != nil {
		return m.DeviceModel
	}
	return nil
}

type CreateDeviceModelResponse struct {
	DeviceModel          *DeviceModel `protobuf:"bytes,1,opt,name=device_model,json=deviceModel" json:"device_model,omitempty", bson:"device_model,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateDeviceModelResponse) Reset()         { *m = CreateDeviceModelResponse{} }
func (m *CreateDeviceModelResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDeviceModelResponse) ProtoMessage()    {}
func (*CreateDeviceModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{8}
}
func (m *CreateDeviceModelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceModelResponse.Unmarshal(m, b)
}
func (m *CreateDeviceModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceModelResponse.Marshal(b, m, deterministic)
}
func (dst *CreateDeviceModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceModelResponse.Merge(dst, src)
}
func (m *CreateDeviceModelResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceModelResponse.Size(m)
}
func (m *CreateDeviceModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceModelResponse proto.InternalMessageInfo

func (m *CreateDeviceModelResponse) GetDeviceModel() *DeviceModel {
	if m != nil {
		return m.DeviceModel
	}
	return nil
}

type GetDeviceModelRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	DeviceModelID        string   `protobuf:"bytes,2,opt,name=deviceModelID" json:"deviceModelID,omitempty", bson:"deviceModelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceModelRequest) Reset()         { *m = GetDeviceModelRequest{} }
func (m *GetDeviceModelRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceModelRequest) ProtoMessage()    {}
func (*GetDeviceModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{9}
}
func (m *GetDeviceModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceModelRequest.Unmarshal(m, b)
}
func (m *GetDeviceModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceModelRequest.Marshal(b, m, deterministic)
}
func (dst *GetDeviceModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceModelRequest.Merge(dst, src)
}
func (m *GetDeviceModelRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceModelRequest.Size(m)
}
func (m *GetDeviceModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceModelRequest proto.InternalMessageInfo

func (m *GetDeviceModelRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDeviceModelRequest) GetDeviceModelID() string {
	if m != nil {
		return m.DeviceModelID
	}
	return ""
}

type GetDeviceModelResponse struct {
	DeviceModel          *DeviceModel `protobuf:"bytes,1,opt,name=device_model,json=deviceModel" json:"device_model,omitempty", bson:"device_model,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetDeviceModelResponse) Reset()         { *m = GetDeviceModelResponse{} }
func (m *GetDeviceModelResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceModelResponse) ProtoMessage()    {}
func (*GetDeviceModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{10}
}
func (m *GetDeviceModelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceModelResponse.Unmarshal(m, b)
}
func (m *GetDeviceModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceModelResponse.Marshal(b, m, deterministic)
}
func (dst *GetDeviceModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceModelResponse.Merge(dst, src)
}
func (m *GetDeviceModelResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceModelResponse.Size(m)
}
func (m *GetDeviceModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceModelResponse proto.InternalMessageInfo

func (m *GetDeviceModelResponse) GetDeviceModel() *DeviceModel {
	if m != nil {
		return m.DeviceModel
	}
	return nil
}

type GetDeviceModelWithNameRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	DeviceModelName      string   `protobuf:"bytes,2,opt,name=device_model_name,json=deviceModelName" json:"device_model_name,omitempty", bson:"device_model_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceModelWithNameRequest) Reset()         { *m = GetDeviceModelWithNameRequest{} }
func (m *GetDeviceModelWithNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceModelWithNameRequest) ProtoMessage()    {}
func (*GetDeviceModelWithNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{11}
}
func (m *GetDeviceModelWithNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceModelWithNameRequest.Unmarshal(m, b)
}
func (m *GetDeviceModelWithNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceModelWithNameRequest.Marshal(b, m, deterministic)
}
func (dst *GetDeviceModelWithNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceModelWithNameRequest.Merge(dst, src)
}
func (m *GetDeviceModelWithNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceModelWithNameRequest.Size(m)
}
func (m *GetDeviceModelWithNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceModelWithNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceModelWithNameRequest proto.InternalMessageInfo

func (m *GetDeviceModelWithNameRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDeviceModelWithNameRequest) GetDeviceModelName() string {
	if m != nil {
		return m.DeviceModelName
	}
	return ""
}

type GetDeviceModelWithNameResponse struct {
	DeviceModel          *DeviceModel `protobuf:"bytes,1,opt,name=device_model,json=deviceModel" json:"device_model,omitempty", bson:"device_model,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetDeviceModelWithNameResponse) Reset()         { *m = GetDeviceModelWithNameResponse{} }
func (m *GetDeviceModelWithNameResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceModelWithNameResponse) ProtoMessage()    {}
func (*GetDeviceModelWithNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{12}
}
func (m *GetDeviceModelWithNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceModelWithNameResponse.Unmarshal(m, b)
}
func (m *GetDeviceModelWithNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceModelWithNameResponse.Marshal(b, m, deterministic)
}
func (dst *GetDeviceModelWithNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceModelWithNameResponse.Merge(dst, src)
}
func (m *GetDeviceModelWithNameResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceModelWithNameResponse.Size(m)
}
func (m *GetDeviceModelWithNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceModelWithNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceModelWithNameResponse proto.InternalMessageInfo

func (m *GetDeviceModelWithNameResponse) GetDeviceModel() *DeviceModel {
	if m != nil {
		return m.DeviceModel
	}
	return nil
}

type DeleteDeviceModelRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	DeviceModelID        string   `protobuf:"bytes,2,opt,name=deviceModelID" json:"deviceModelID,omitempty", bson:"deviceModelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceModelRequest) Reset()         { *m = DeleteDeviceModelRequest{} }
func (m *DeleteDeviceModelRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceModelRequest) ProtoMessage()    {}
func (*DeleteDeviceModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{13}
}
func (m *DeleteDeviceModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceModelRequest.Unmarshal(m, b)
}
func (m *DeleteDeviceModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceModelRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteDeviceModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceModelRequest.Merge(dst, src)
}
func (m *DeleteDeviceModelRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceModelRequest.Size(m)
}
func (m *DeleteDeviceModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceModelRequest proto.InternalMessageInfo

func (m *DeleteDeviceModelRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *DeleteDeviceModelRequest) GetDeviceModelID() string {
	if m != nil {
		return m.DeviceModelID
	}
	return ""
}

type DeleteDeviceModelResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceModelResponse) Reset()         { *m = DeleteDeviceModelResponse{} }
func (m *DeleteDeviceModelResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceModelResponse) ProtoMessage()    {}
func (*DeleteDeviceModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{14}
}
func (m *DeleteDeviceModelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceModelResponse.Unmarshal(m, b)
}
func (m *DeleteDeviceModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceModelResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteDeviceModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceModelResponse.Merge(dst, src)
}
func (m *DeleteDeviceModelResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceModelResponse.Size(m)
}
func (m *DeleteDeviceModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceModelResponse proto.InternalMessageInfo

type UpdateDeviceModelRequest struct {
	UserID               string       `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	DeviceModelID        string       `protobuf:"bytes,2,opt,name=deviceModelID" json:"deviceModelID,omitempty", bson:"deviceModelID,omitempty"`
	DeviceModel          *DeviceModel `protobuf:"bytes,3,opt,name=device_model,json=deviceModel" json:"device_model,omitempty", bson:"device_model,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateDeviceModelRequest) Reset()         { *m = UpdateDeviceModelRequest{} }
func (m *UpdateDeviceModelRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDeviceModelRequest) ProtoMessage()    {}
func (*UpdateDeviceModelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{15}
}
func (m *UpdateDeviceModelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeviceModelRequest.Unmarshal(m, b)
}
func (m *UpdateDeviceModelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeviceModelRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateDeviceModelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeviceModelRequest.Merge(dst, src)
}
func (m *UpdateDeviceModelRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDeviceModelRequest.Size(m)
}
func (m *UpdateDeviceModelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeviceModelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeviceModelRequest proto.InternalMessageInfo

func (m *UpdateDeviceModelRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateDeviceModelRequest) GetDeviceModelID() string {
	if m != nil {
		return m.DeviceModelID
	}
	return ""
}

func (m *UpdateDeviceModelRequest) GetDeviceModel() *DeviceModel {
	if m != nil {
		return m.DeviceModel
	}
	return nil
}

type UpdateDeviceModelResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDeviceModelResponse) Reset()         { *m = UpdateDeviceModelResponse{} }
func (m *UpdateDeviceModelResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateDeviceModelResponse) ProtoMessage()    {}
func (*UpdateDeviceModelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{16}
}
func (m *UpdateDeviceModelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeviceModelResponse.Unmarshal(m, b)
}
func (m *UpdateDeviceModelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeviceModelResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateDeviceModelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeviceModelResponse.Merge(dst, src)
}
func (m *UpdateDeviceModelResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateDeviceModelResponse.Size(m)
}
func (m *UpdateDeviceModelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeviceModelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeviceModelResponse proto.InternalMessageInfo

type GetDeviceModelsRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceModelsRequest) Reset()         { *m = GetDeviceModelsRequest{} }
func (m *GetDeviceModelsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceModelsRequest) ProtoMessage()    {}
func (*GetDeviceModelsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{17}
}
func (m *GetDeviceModelsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceModelsRequest.Unmarshal(m, b)
}
func (m *GetDeviceModelsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceModelsRequest.Marshal(b, m, deterministic)
}
func (dst *GetDeviceModelsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceModelsRequest.Merge(dst, src)
}
func (m *GetDeviceModelsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceModelsRequest.Size(m)
}
func (m *GetDeviceModelsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceModelsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceModelsRequest proto.InternalMessageInfo

func (m *GetDeviceModelsRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetDeviceModelsResponse struct {
	DeviceModels         []*DeviceModel `protobuf:"bytes,1,rep,name=device_models,json=deviceModels" json:"device_models,omitempty", bson:"device_models,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetDeviceModelsResponse) Reset()         { *m = GetDeviceModelsResponse{} }
func (m *GetDeviceModelsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceModelsResponse) ProtoMessage()    {}
func (*GetDeviceModelsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{18}
}
func (m *GetDeviceModelsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceModelsResponse.Unmarshal(m, b)
}
func (m *GetDeviceModelsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceModelsResponse.Marshal(b, m, deterministic)
}
func (dst *GetDeviceModelsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceModelsResponse.Merge(dst, src)
}
func (m *GetDeviceModelsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceModelsResponse.Size(m)
}
func (m *GetDeviceModelsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceModelsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceModelsResponse proto.InternalMessageInfo

func (m *GetDeviceModelsResponse) GetDeviceModels() []*DeviceModel {
	if m != nil {
		return m.DeviceModels
	}
	return nil
}

// Device apis
type AddDeviceRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	Device               *Device  `protobuf:"bytes,2,opt,name=device" json:"device,omitempty", bson:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDeviceRequest) Reset()         { *m = AddDeviceRequest{} }
func (m *AddDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*AddDeviceRequest) ProtoMessage()    {}
func (*AddDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{19}
}
func (m *AddDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceRequest.Unmarshal(m, b)
}
func (m *AddDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceRequest.Marshal(b, m, deterministic)
}
func (dst *AddDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceRequest.Merge(dst, src)
}
func (m *AddDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_AddDeviceRequest.Size(m)
}
func (m *AddDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceRequest proto.InternalMessageInfo

func (m *AddDeviceRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AddDeviceRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type AddDeviceResponse struct {
	Device               *Device  `protobuf:"bytes,1,opt,name=device" json:"device,omitempty", bson:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDeviceResponse) Reset()         { *m = AddDeviceResponse{} }
func (m *AddDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*AddDeviceResponse) ProtoMessage()    {}
func (*AddDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{20}
}
func (m *AddDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDeviceResponse.Unmarshal(m, b)
}
func (m *AddDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDeviceResponse.Marshal(b, m, deterministic)
}
func (dst *AddDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDeviceResponse.Merge(dst, src)
}
func (m *AddDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_AddDeviceResponse.Size(m)
}
func (m *AddDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddDeviceResponse proto.InternalMessageInfo

func (m *AddDeviceResponse) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type GetDeviceRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	DeviceID             string   `protobuf:"bytes,2,opt,name=deviceID" json:"deviceID,omitempty", bson:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceRequest) Reset()         { *m = GetDeviceRequest{} }
func (m *GetDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceRequest) ProtoMessage()    {}
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{21}
}
func (m *GetDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceRequest.Unmarshal(m, b)
}
func (m *GetDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceRequest.Marshal(b, m, deterministic)
}
func (dst *GetDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceRequest.Merge(dst, src)
}
func (m *GetDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceRequest.Size(m)
}
func (m *GetDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceRequest proto.InternalMessageInfo

func (m *GetDeviceRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDeviceRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

type GetDeviceResponse struct {
	Device               *Device  `protobuf:"bytes,1,opt,name=device" json:"device,omitempty", bson:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceResponse) Reset()         { *m = GetDeviceResponse{} }
func (m *GetDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceResponse) ProtoMessage()    {}
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{22}
}
func (m *GetDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceResponse.Unmarshal(m, b)
}
func (m *GetDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceResponse.Marshal(b, m, deterministic)
}
func (dst *GetDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceResponse.Merge(dst, src)
}
func (m *GetDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceResponse.Size(m)
}
func (m *GetDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceResponse proto.InternalMessageInfo

func (m *GetDeviceResponse) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type UpdateDeviceRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	Device               *Device  `protobuf:"bytes,2,opt,name=device" json:"device,omitempty", bson:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDeviceRequest) Reset()         { *m = UpdateDeviceRequest{} }
func (m *UpdateDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDeviceRequest) ProtoMessage()    {}
func (*UpdateDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{23}
}
func (m *UpdateDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeviceRequest.Unmarshal(m, b)
}
func (m *UpdateDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeviceRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeviceRequest.Merge(dst, src)
}
func (m *UpdateDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDeviceRequest.Size(m)
}
func (m *UpdateDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeviceRequest proto.InternalMessageInfo

func (m *UpdateDeviceRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateDeviceRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type UpdateDeviceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDeviceResponse) Reset()         { *m = UpdateDeviceResponse{} }
func (m *UpdateDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateDeviceResponse) ProtoMessage()    {}
func (*UpdateDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{24}
}
func (m *UpdateDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeviceResponse.Unmarshal(m, b)
}
func (m *UpdateDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeviceResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeviceResponse.Merge(dst, src)
}
func (m *UpdateDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateDeviceResponse.Size(m)
}
func (m *UpdateDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeviceResponse proto.InternalMessageInfo

type GetDevicesRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	DeviceIDs            []string `protobuf:"bytes,2,rep,name=deviceIDs" json:"deviceIDs,omitempty", bson:"deviceIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDevicesRequest) Reset()         { *m = GetDevicesRequest{} }
func (m *GetDevicesRequest) String() string { return proto.CompactTextString(m) }
func (*GetDevicesRequest) ProtoMessage()    {}
func (*GetDevicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{25}
}
func (m *GetDevicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDevicesRequest.Unmarshal(m, b)
}
func (m *GetDevicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDevicesRequest.Marshal(b, m, deterministic)
}
func (dst *GetDevicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDevicesRequest.Merge(dst, src)
}
func (m *GetDevicesRequest) XXX_Size() int {
	return xxx_messageInfo_GetDevicesRequest.Size(m)
}
func (m *GetDevicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDevicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDevicesRequest proto.InternalMessageInfo

func (m *GetDevicesRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDevicesRequest) GetDeviceIDs() []string {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

type GetDevicesResponse struct {
	Devices              []*Device `protobuf:"bytes,1,rep,name=devices" json:"devices,omitempty", bson:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetDevicesResponse) Reset()         { *m = GetDevicesResponse{} }
func (m *GetDevicesResponse) String() string { return proto.CompactTextString(m) }
func (*GetDevicesResponse) ProtoMessage()    {}
func (*GetDevicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{26}
}
func (m *GetDevicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDevicesResponse.Unmarshal(m, b)
}
func (m *GetDevicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDevicesResponse.Marshal(b, m, deterministic)
}
func (dst *GetDevicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDevicesResponse.Merge(dst, src)
}
func (m *GetDevicesResponse) XXX_Size() int {
	return xxx_messageInfo_GetDevicesResponse.Size(m)
}
func (m *GetDevicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDevicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDevicesResponse proto.InternalMessageInfo

func (m *GetDevicesResponse) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type DeleteDeviceRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	DeviceID             string   `protobuf:"bytes,2,opt,name=deviceID" json:"deviceID,omitempty", bson:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceRequest) Reset()         { *m = DeleteDeviceRequest{} }
func (m *DeleteDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceRequest) ProtoMessage()    {}
func (*DeleteDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{27}
}
func (m *DeleteDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceRequest.Unmarshal(m, b)
}
func (m *DeleteDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceRequest.Merge(dst, src)
}
func (m *DeleteDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceRequest.Size(m)
}
func (m *DeleteDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceRequest proto.InternalMessageInfo

func (m *DeleteDeviceRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *DeleteDeviceRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

type DeleteDeviceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceResponse) Reset()         { *m = DeleteDeviceResponse{} }
func (m *DeleteDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceResponse) ProtoMessage()    {}
func (*DeleteDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{28}
}
func (m *DeleteDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceResponse.Unmarshal(m, b)
}
func (m *DeleteDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceResponse.Merge(dst, src)
}
func (m *DeleteDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceResponse.Size(m)
}
func (m *DeleteDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceResponse proto.InternalMessageInfo

type SetDeviceStatusRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	DeviceID             string   `protobuf:"bytes,2,opt,name=deviceID" json:"deviceID,omitempty", bson:"deviceID,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status" json:"status,omitempty", bson:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDeviceStatusRequest) Reset()         { *m = SetDeviceStatusRequest{} }
func (m *SetDeviceStatusRequest) String() string { return proto.CompactTextString(m) }
func (*SetDeviceStatusRequest) ProtoMessage()    {}
func (*SetDeviceStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{29}
}
func (m *SetDeviceStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDeviceStatusRequest.Unmarshal(m, b)
}
func (m *SetDeviceStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDeviceStatusRequest.Marshal(b, m, deterministic)
}
func (dst *SetDeviceStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDeviceStatusRequest.Merge(dst, src)
}
func (m *SetDeviceStatusRequest) XXX_Size() int {
	return xxx_messageInfo_SetDeviceStatusRequest.Size(m)
}
func (m *SetDeviceStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDeviceStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDeviceStatusRequest proto.InternalMessageInfo

func (m *SetDeviceStatusRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SetDeviceStatusRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *SetDeviceStatusRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type SetDeviceStatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDeviceStatusResponse) Reset()         { *m = SetDeviceStatusResponse{} }
func (m *SetDeviceStatusResponse) String() string { return proto.CompactTextString(m) }
func (*SetDeviceStatusResponse) ProtoMessage()    {}
func (*SetDeviceStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{30}
}
func (m *SetDeviceStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDeviceStatusResponse.Unmarshal(m, b)
}
func (m *SetDeviceStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDeviceStatusResponse.Marshal(b, m, deterministic)
}
func (dst *SetDeviceStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDeviceStatusResponse.Merge(dst, src)
}
func (m *SetDeviceStatusResponse) XXX_Size() int {
	return xxx_messageInfo_SetDeviceStatusResponse.Size(m)
}
func (m *SetDeviceStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDeviceStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetDeviceStatusResponse proto.InternalMessageInfo

type GetDeviceLogRequest struct {
	UserID               string               `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	DeviceID             string               `protobuf:"bytes,2,opt,name=deviceID" json:"deviceID,omitempty", bson:"deviceID,omitempty"`
	Since                *timestamp.Timestamp `protobuf:"bytes,3,opt,name=since" json:"since,omitempty", bson:"since,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetDeviceLogRequest) Reset()         { *m = GetDeviceLogRequest{} }
func (m *GetDeviceLogRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceLogRequest) ProtoMessage()    {}
func (*GetDeviceLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{31}
}
func (m *GetDeviceLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceLogRequest.Unmarshal(m, b)
}
func (m *GetDeviceLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceLogRequest.Marshal(b, m, deterministic)
}
func (dst *GetDeviceLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceLogRequest.Merge(dst, src)
}
func (m *GetDeviceLogRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceLogRequest.Size(m)
}
func (m *GetDeviceLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceLogRequest proto.InternalMessageInfo

func (m *GetDeviceLogRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDeviceLogRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *GetDeviceLogRequest) GetSince() *timestamp.Timestamp {
	if m != nil {
		return m.Since
	}
	return nil
}

type GetDeviceLogResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceLogResponse) Reset()         { *m = GetDeviceLogResponse{} }
func (m *GetDeviceLogResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceLogResponse) ProtoMessage()    {}
func (*GetDeviceLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{32}
}
func (m *GetDeviceLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceLogResponse.Unmarshal(m, b)
}
func (m *GetDeviceLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceLogResponse.Marshal(b, m, deterministic)
}
func (dst *GetDeviceLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceLogResponse.Merge(dst, src)
}
func (m *GetDeviceLogResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceLogResponse.Size(m)
}
func (m *GetDeviceLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceLogResponse proto.InternalMessageInfo

type GetDeviceMetricsRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	DeviceID             string   `protobuf:"bytes,2,opt,name=deviceID" json:"deviceID,omitempty", bson:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceMetricsRequest) Reset()         { *m = GetDeviceMetricsRequest{} }
func (m *GetDeviceMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceMetricsRequest) ProtoMessage()    {}
func (*GetDeviceMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{33}
}
func (m *GetDeviceMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceMetricsRequest.Unmarshal(m, b)
}
func (m *GetDeviceMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceMetricsRequest.Marshal(b, m, deterministic)
}
func (dst *GetDeviceMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceMetricsRequest.Merge(dst, src)
}
func (m *GetDeviceMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceMetricsRequest.Size(m)
}
func (m *GetDeviceMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceMetricsRequest proto.InternalMessageInfo

func (m *GetDeviceMetricsRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDeviceMetricsRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

type GetDeviceMetricsResponse struct {
	DeviceMetrics        *DeviceMetrics `protobuf:"bytes,1,opt,name=device_metrics,json=deviceMetrics" json:"device_metrics,omitempty", bson:"device_metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetDeviceMetricsResponse) Reset()         { *m = GetDeviceMetricsResponse{} }
func (m *GetDeviceMetricsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceMetricsResponse) ProtoMessage()    {}
func (*GetDeviceMetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{34}
}
func (m *GetDeviceMetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceMetricsResponse.Unmarshal(m, b)
}
func (m *GetDeviceMetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceMetricsResponse.Marshal(b, m, deterministic)
}
func (dst *GetDeviceMetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceMetricsResponse.Merge(dst, src)
}
func (m *GetDeviceMetricsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceMetricsResponse.Size(m)
}
func (m *GetDeviceMetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceMetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceMetricsResponse proto.InternalMessageInfo

func (m *GetDeviceMetricsResponse) GetDeviceMetrics() *DeviceMetrics {
	if m != nil {
		return m.DeviceMetrics
	}
	return nil
}

type PostDeviceMessageRequest struct {
	UserID               string         `protobuf:"bytes,1,opt,name=userID" json:"userID,omitempty", bson:"userID,omitempty"`
	DeviceID             string         `protobuf:"bytes,2,opt,name=deviceID" json:"deviceID,omitempty", bson:"deviceID,omitempty"`
	DeviceMessage        *DeviceMessage `protobuf:"bytes,3,opt,name=device_message,json=deviceMessage" json:"device_message,omitempty", bson:"device_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PostDeviceMessageRequest) Reset()         { *m = PostDeviceMessageRequest{} }
func (m *PostDeviceMessageRequest) String() string { return proto.CompactTextString(m) }
func (*PostDeviceMessageRequest) ProtoMessage()    {}
func (*PostDeviceMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{35}
}
func (m *PostDeviceMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostDeviceMessageRequest.Unmarshal(m, b)
}
func (m *PostDeviceMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostDeviceMessageRequest.Marshal(b, m, deterministic)
}
func (dst *PostDeviceMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostDeviceMessageRequest.Merge(dst, src)
}
func (m *PostDeviceMessageRequest) XXX_Size() int {
	return xxx_messageInfo_PostDeviceMessageRequest.Size(m)
}
func (m *PostDeviceMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostDeviceMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostDeviceMessageRequest proto.InternalMessageInfo

func (m *PostDeviceMessageRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *PostDeviceMessageRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *PostDeviceMessageRequest) GetDeviceMessage() *DeviceMessage {
	if m != nil {
		return m.DeviceMessage
	}
	return nil
}

type PostDeviceMessageResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostDeviceMessageResponse) Reset()         { *m = PostDeviceMessageResponse{} }
func (m *PostDeviceMessageResponse) String() string { return proto.CompactTextString(m) }
func (*PostDeviceMessageResponse) ProtoMessage()    {}
func (*PostDeviceMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dmms_2cb92092de215df7, []int{36}
}
func (m *PostDeviceMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostDeviceMessageResponse.Unmarshal(m, b)
}
func (m *PostDeviceMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostDeviceMessageResponse.Marshal(b, m, deterministic)
}
func (dst *PostDeviceMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostDeviceMessageResponse.Merge(dst, src)
}
func (m *PostDeviceMessageResponse) XXX_Size() int {
	return xxx_messageInfo_PostDeviceMessageResponse.Size(m)
}
func (m *PostDeviceMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostDeviceMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostDeviceMessageResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Device)(nil), "grpc.dmms.v1.Device")
	proto.RegisterType((*Endpoint)(nil), "grpc.dmms.v1.Endpoint")
	proto.RegisterMapType((map[string]string)(nil), "grpc.dmms.v1.Endpoint.ModelsEntry")
	proto.RegisterType((*DataModel)(nil), "grpc.dmms.v1.DataModel")
	proto.RegisterType((*DataModelField)(nil), "grpc.dmms.v1.DataModelField")
	proto.RegisterType((*DeviceModel)(nil), "grpc.dmms.v1.DeviceModel")
	proto.RegisterType((*DeviceMetrics)(nil), "grpc.dmms.v1.DeviceMetrics")
	proto.RegisterMapType((map[string]int32)(nil), "grpc.dmms.v1.DeviceMetrics.MetricsEntry")
	proto.RegisterType((*DeviceMessage)(nil), "grpc.dmms.v1.DeviceMessage")
	proto.RegisterType((*CreateDeviceModelRequest)(nil), "grpc.dmms.v1.CreateDeviceModelRequest")
	proto.RegisterType((*CreateDeviceModelResponse)(nil), "grpc.dmms.v1.CreateDeviceModelResponse")
	proto.RegisterType((*GetDeviceModelRequest)(nil), "grpc.dmms.v1.GetDeviceModelRequest")
	proto.RegisterType((*GetDeviceModelResponse)(nil), "grpc.dmms.v1.GetDeviceModelResponse")
	proto.RegisterType((*GetDeviceModelWithNameRequest)(nil), "grpc.dmms.v1.GetDeviceModelWithNameRequest")
	proto.RegisterType((*GetDeviceModelWithNameResponse)(nil), "grpc.dmms.v1.GetDeviceModelWithNameResponse")
	proto.RegisterType((*DeleteDeviceModelRequest)(nil), "grpc.dmms.v1.DeleteDeviceModelRequest")
	proto.RegisterType((*DeleteDeviceModelResponse)(nil), "grpc.dmms.v1.DeleteDeviceModelResponse")
	proto.RegisterType((*UpdateDeviceModelRequest)(nil), "grpc.dmms.v1.UpdateDeviceModelRequest")
	proto.RegisterType((*UpdateDeviceModelResponse)(nil), "grpc.dmms.v1.UpdateDeviceModelResponse")
	proto.RegisterType((*GetDeviceModelsRequest)(nil), "grpc.dmms.v1.GetDeviceModelsRequest")
	proto.RegisterType((*GetDeviceModelsResponse)(nil), "grpc.dmms.v1.GetDeviceModelsResponse")
	proto.RegisterType((*AddDeviceRequest)(nil), "grpc.dmms.v1.AddDeviceRequest")
	proto.RegisterType((*AddDeviceResponse)(nil), "grpc.dmms.v1.AddDeviceResponse")
	proto.RegisterType((*GetDeviceRequest)(nil), "grpc.dmms.v1.GetDeviceRequest")
	proto.RegisterType((*GetDeviceResponse)(nil), "grpc.dmms.v1.GetDeviceResponse")
	proto.RegisterType((*UpdateDeviceRequest)(nil), "grpc.dmms.v1.UpdateDeviceRequest")
	proto.RegisterType((*UpdateDeviceResponse)(nil), "grpc.dmms.v1.UpdateDeviceResponse")
	proto.RegisterType((*GetDevicesRequest)(nil), "grpc.dmms.v1.GetDevicesRequest")
	proto.RegisterType((*GetDevicesResponse)(nil), "grpc.dmms.v1.GetDevicesResponse")
	proto.RegisterType((*DeleteDeviceRequest)(nil), "grpc.dmms.v1.DeleteDeviceRequest")
	proto.RegisterType((*DeleteDeviceResponse)(nil), "grpc.dmms.v1.DeleteDeviceResponse")
	proto.RegisterType((*SetDeviceStatusRequest)(nil), "grpc.dmms.v1.SetDeviceStatusRequest")
	proto.RegisterType((*SetDeviceStatusResponse)(nil), "grpc.dmms.v1.SetDeviceStatusResponse")
	proto.RegisterType((*GetDeviceLogRequest)(nil), "grpc.dmms.v1.GetDeviceLogRequest")
	proto.RegisterType((*GetDeviceLogResponse)(nil), "grpc.dmms.v1.GetDeviceLogResponse")
	proto.RegisterType((*GetDeviceMetricsRequest)(nil), "grpc.dmms.v1.GetDeviceMetricsRequest")
	proto.RegisterType((*GetDeviceMetricsResponse)(nil), "grpc.dmms.v1.GetDeviceMetricsResponse")
	proto.RegisterType((*PostDeviceMessageRequest)(nil), "grpc.dmms.v1.PostDeviceMessageRequest")
	proto.RegisterType((*PostDeviceMessageResponse)(nil), "grpc.dmms.v1.PostDeviceMessageResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DMMSClient is the client API for DMMS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DMMSClient interface {
	// DeviceModel
	CreateDeviceModel(ctx context.Context, in *CreateDeviceModelRequest, opts ...grpc.CallOption) (*CreateDeviceModelResponse, error)
	GetDeviceModel(ctx context.Context, in *GetDeviceModelRequest, opts ...grpc.CallOption) (*GetDeviceModelResponse, error)
	GetDeviceModelWithName(ctx context.Context, in *GetDeviceModelWithNameRequest, opts ...grpc.CallOption) (*GetDeviceModelWithNameResponse, error)
	DeleteDeviceModel(ctx context.Context, in *DeleteDeviceModelRequest, opts ...grpc.CallOption) (*DeleteDeviceModelResponse, error)
	UpdateDeviceModel(ctx context.Context, in *UpdateDeviceModelRequest, opts ...grpc.CallOption) (*UpdateDeviceModelResponse, error)
	GetDeviceModels(ctx context.Context, in *GetDeviceModelsRequest, opts ...grpc.CallOption) (*GetDeviceModelsResponse, error)
	// Device Management
	AddDevice(ctx context.Context, in *AddDeviceRequest, opts ...grpc.CallOption) (*AddDeviceResponse, error)
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error)
	UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*UpdateDeviceResponse, error)
	GetDevices(ctx context.Context, in *GetDevicesRequest, opts ...grpc.CallOption) (*GetDevicesResponse, error)
	DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error)
	SetDeviceStatus(ctx context.Context, in *SetDeviceStatusRequest, opts ...grpc.CallOption) (*SetDeviceStatusResponse, error)
	GetDeviceLog(ctx context.Context, in *GetDeviceLogRequest, opts ...grpc.CallOption) (*GetDeviceLogResponse, error)
	GetDeviceMetrics(ctx context.Context, in *GetDeviceMetricsRequest, opts ...grpc.CallOption) (*GetDeviceMetricsResponse, error)
	PostDeviceMessage(ctx context.Context, in *PostDeviceMessageRequest, opts ...grpc.CallOption) (*PostDeviceMessageResponse, error)
}

type dMMSClient struct {
	cc *grpc.ClientConn
}

func NewDMMSClient(cc *grpc.ClientConn) DMMSClient {
	return &dMMSClient{cc}
}

func (c *dMMSClient) CreateDeviceModel(ctx context.Context, in *CreateDeviceModelRequest, opts ...grpc.CallOption) (*CreateDeviceModelResponse, error) {
	out := new(CreateDeviceModelResponse)
	err := c.cc.Invoke(ctx, "/grpc.dmms.v1.DMMS/CreateDeviceModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMMSClient) GetDeviceModel(ctx context.Context, in *GetDeviceModelRequest, opts ...grpc.CallOption) (*GetDeviceModelResponse, error) {
	out := new(GetDeviceModelResponse)
	err := c.cc.Invoke(ctx, "/grpc.dmms.v1.DMMS/GetDeviceModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMMSClient) GetDeviceModelWithName(ctx context.Context, in *GetDeviceModelWithNameRequest, opts ...grpc.CallOption) (*GetDeviceModelWithNameResponse, error) {
	out := new(GetDeviceModelWithNameResponse)
	err := c.cc.Invoke(ctx, "/grpc.dmms.v1.DMMS/GetDeviceModelWithName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMMSClient) DeleteDeviceModel(ctx context.Context, in *DeleteDeviceModelRequest, opts ...grpc.CallOption) (*DeleteDeviceModelResponse, error) {
	out := new(DeleteDeviceModelResponse)
	err := c.cc.Invoke(ctx, "/grpc.dmms.v1.DMMS/DeleteDeviceModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMMSClient) UpdateDeviceModel(ctx context.Context, in *UpdateDeviceModelRequest, opts ...grpc.CallOption) (*UpdateDeviceModelResponse, error) {
	out := new(UpdateDeviceModelResponse)
	err := c.cc.Invoke(ctx, "/grpc.dmms.v1.DMMS/UpdateDeviceModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMMSClient) GetDeviceModels(ctx context.Context, in *GetDeviceModelsRequest, opts ...grpc.CallOption) (*GetDeviceModelsResponse, error) {
	out := new(GetDeviceModelsResponse)
	err := c.cc.Invoke(ctx, "/grpc.dmms.v1.DMMS/GetDeviceModels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMMSClient) AddDevice(ctx context.Context, in *AddDeviceRequest, opts ...grpc.CallOption) (*AddDeviceResponse, error) {
	out := new(AddDeviceResponse)
	err := c.cc.Invoke(ctx, "/grpc.dmms.v1.DMMS/AddDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMMSClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error) {
	out := new(GetDeviceResponse)
	err := c.cc.Invoke(ctx, "/grpc.dmms.v1.DMMS/GetDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMMSClient) UpdateDevice(ctx context.Context, in *UpdateDeviceRequest, opts ...grpc.CallOption) (*UpdateDeviceResponse, error) {
	out := new(UpdateDeviceResponse)
	err := c.cc.Invoke(ctx, "/grpc.dmms.v1.DMMS/UpdateDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMMSClient) GetDevices(ctx context.Context, in *GetDevicesRequest, opts ...grpc.CallOption) (*GetDevicesResponse, error) {
	out := new(GetDevicesResponse)
	err := c.cc.Invoke(ctx, "/grpc.dmms.v1.DMMS/GetDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMMSClient) DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error) {
	out := new(DeleteDeviceResponse)
	err := c.cc.Invoke(ctx, "/grpc.dmms.v1.DMMS/DeleteDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMMSClient) SetDeviceStatus(ctx context.Context, in *SetDeviceStatusRequest, opts ...grpc.CallOption) (*SetDeviceStatusResponse, error) {
	out := new(SetDeviceStatusResponse)
	err := c.cc.Invoke(ctx, "/grpc.dmms.v1.DMMS/SetDeviceStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMMSClient) GetDeviceLog(ctx context.Context, in *GetDeviceLogRequest, opts ...grpc.CallOption) (*GetDeviceLogResponse, error) {
	out := new(GetDeviceLogResponse)
	err := c.cc.Invoke(ctx, "/grpc.dmms.v1.DMMS/GetDeviceLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMMSClient) GetDeviceMetrics(ctx context.Context, in *GetDeviceMetricsRequest, opts ...grpc.CallOption) (*GetDeviceMetricsResponse, error) {
	out := new(GetDeviceMetricsResponse)
	err := c.cc.Invoke(ctx, "/grpc.dmms.v1.DMMS/GetDeviceMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dMMSClient) PostDeviceMessage(ctx context.Context, in *PostDeviceMessageRequest, opts ...grpc.CallOption) (*PostDeviceMessageResponse, error) {
	out := new(PostDeviceMessageResponse)
	err := c.cc.Invoke(ctx, "/grpc.dmms.v1.DMMS/PostDeviceMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DMMSServer is the server API for DMMS service.
type DMMSServer interface {
	// DeviceModel
	CreateDeviceModel(context.Context, *CreateDeviceModelRequest) (*CreateDeviceModelResponse, error)
	GetDeviceModel(context.Context, *GetDeviceModelRequest) (*GetDeviceModelResponse, error)
	GetDeviceModelWithName(context.Context, *GetDeviceModelWithNameRequest) (*GetDeviceModelWithNameResponse, error)
	DeleteDeviceModel(context.Context, *DeleteDeviceModelRequest) (*DeleteDeviceModelResponse, error)
	UpdateDeviceModel(context.Context, *UpdateDeviceModelRequest) (*UpdateDeviceModelResponse, error)
	GetDeviceModels(context.Context, *GetDeviceModelsRequest) (*GetDeviceModelsResponse, error)
	// Device Management
	AddDevice(context.Context, *AddDeviceRequest) (*AddDeviceResponse, error)
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
	UpdateDevice(context.Context, *UpdateDeviceRequest) (*UpdateDeviceResponse, error)
	GetDevices(context.Context, *GetDevicesRequest) (*GetDevicesResponse, error)
	DeleteDevice(context.Context, *DeleteDeviceRequest) (*DeleteDeviceResponse, error)
	SetDeviceStatus(context.Context, *SetDeviceStatusRequest) (*SetDeviceStatusResponse, error)
	GetDeviceLog(context.Context, *GetDeviceLogRequest) (*GetDeviceLogResponse, error)
	GetDeviceMetrics(context.Context, *GetDeviceMetricsRequest) (*GetDeviceMetricsResponse, error)
	PostDeviceMessage(context.Context, *PostDeviceMessageRequest) (*PostDeviceMessageResponse, error)
}

func RegisterDMMSServer(s *grpc.Server, srv DMMSServer) {
	s.RegisterService(&_DMMS_serviceDesc, srv)
}

func _DMMS_CreateDeviceModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeviceModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMMSServer).CreateDeviceModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.dmms.v1.DMMS/CreateDeviceModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMMSServer).CreateDeviceModel(ctx, req.(*CreateDeviceModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMMS_GetDeviceModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMMSServer).GetDeviceModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.dmms.v1.DMMS/GetDeviceModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMMSServer).GetDeviceModel(ctx, req.(*GetDeviceModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMMS_GetDeviceModelWithName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceModelWithNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMMSServer).GetDeviceModelWithName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.dmms.v1.DMMS/GetDeviceModelWithName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMMSServer).GetDeviceModelWithName(ctx, req.(*GetDeviceModelWithNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMMS_DeleteDeviceModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMMSServer).DeleteDeviceModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.dmms.v1.DMMS/DeleteDeviceModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMMSServer).DeleteDeviceModel(ctx, req.(*DeleteDeviceModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMMS_UpdateDeviceModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMMSServer).UpdateDeviceModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.dmms.v1.DMMS/UpdateDeviceModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMMSServer).UpdateDeviceModel(ctx, req.(*UpdateDeviceModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMMS_GetDeviceModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMMSServer).GetDeviceModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.dmms.v1.DMMS/GetDeviceModels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMMSServer).GetDeviceModels(ctx, req.(*GetDeviceModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMMS_AddDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMMSServer).AddDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.dmms.v1.DMMS/AddDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMMSServer).AddDevice(ctx, req.(*AddDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMMS_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMMSServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.dmms.v1.DMMS/GetDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMMSServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMMS_UpdateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMMSServer).UpdateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.dmms.v1.DMMS/UpdateDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMMSServer).UpdateDevice(ctx, req.(*UpdateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMMS_GetDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMMSServer).GetDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.dmms.v1.DMMS/GetDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMMSServer).GetDevices(ctx, req.(*GetDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMMS_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMMSServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.dmms.v1.DMMS/DeleteDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMMSServer).DeleteDevice(ctx, req.(*DeleteDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMMS_SetDeviceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeviceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMMSServer).SetDeviceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.dmms.v1.DMMS/SetDeviceStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMMSServer).SetDeviceStatus(ctx, req.(*SetDeviceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMMS_GetDeviceLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMMSServer).GetDeviceLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.dmms.v1.DMMS/GetDeviceLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMMSServer).GetDeviceLog(ctx, req.(*GetDeviceLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMMS_GetDeviceMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMMSServer).GetDeviceMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.dmms.v1.DMMS/GetDeviceMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMMSServer).GetDeviceMetrics(ctx, req.(*GetDeviceMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DMMS_PostDeviceMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostDeviceMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMMSServer).PostDeviceMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.dmms.v1.DMMS/PostDeviceMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMMSServer).PostDeviceMessage(ctx, req.(*PostDeviceMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DMMS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.dmms.v1.DMMS",
	HandlerType: (*DMMSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeviceModel",
			Handler:    _DMMS_CreateDeviceModel_Handler,
		},
		{
			MethodName: "GetDeviceModel",
			Handler:    _DMMS_GetDeviceModel_Handler,
		},
		{
			MethodName: "GetDeviceModelWithName",
			Handler:    _DMMS_GetDeviceModelWithName_Handler,
		},
		{
			MethodName: "DeleteDeviceModel",
			Handler:    _DMMS_DeleteDeviceModel_Handler,
		},
		{
			MethodName: "UpdateDeviceModel",
			Handler:    _DMMS_UpdateDeviceModel_Handler,
		},
		{
			MethodName: "GetDeviceModels",
			Handler:    _DMMS_GetDeviceModels_Handler,
		},
		{
			MethodName: "AddDevice",
			Handler:    _DMMS_AddDevice_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _DMMS_GetDevice_Handler,
		},
		{
			MethodName: "UpdateDevice",
			Handler:    _DMMS_UpdateDevice_Handler,
		},
		{
			MethodName: "GetDevices",
			Handler:    _DMMS_GetDevices_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _DMMS_DeleteDevice_Handler,
		},
		{
			MethodName: "SetDeviceStatus",
			Handler:    _DMMS_SetDeviceStatus_Handler,
		},
		{
			MethodName: "GetDeviceLog",
			Handler:    _DMMS_GetDeviceLog_Handler,
		},
		{
			MethodName: "GetDeviceMetrics",
			Handler:    _DMMS_GetDeviceMetrics_Handler,
		},
		{
			MethodName: "PostDeviceMessage",
			Handler:    _DMMS_PostDeviceMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dmms.proto",
}

func init() { proto.RegisterFile("dmms.proto", fileDescriptor_dmms_2cb92092de215df7) }

var fileDescriptor_dmms_2cb92092de215df7 = []byte{
	// 1372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xeb, 0x6e, 0x1b, 0xc5,
	0x17, 0xcf, 0xda, 0x8e, 0x2f, 0xc7, 0x4e, 0xd2, 0x4c, 0xf2, 0x77, 0x26, 0x9b, 0xfe, 0x53, 0xb3,
	0x2d, 0x25, 0x82, 0xca, 0x2d, 0x01, 0x01, 0x8d, 0x10, 0x52, 0x12, 0xb7, 0x60, 0xa9, 0xa9, 0xc0,
	0xa1, 0x37, 0x21, 0x6a, 0xb6, 0xde, 0xb1, 0xb3, 0x60, 0x7b, 0xb7, 0x9e, 0x71, 0xa4, 0x88, 0xa7,
	0x80, 0x0f, 0xbc, 0x00, 0x9f, 0x79, 0x0a, 0x9e, 0x87, 0x67, 0x00, 0xed, 0xcc, 0xec, 0x7a, 0x76,
	0xbc, 0x6b, 0x27, 0x75, 0x3e, 0x79, 0x67, 0xe6, 0x5c, 0x7e, 0xe7, 0x37, 0xe7, 0x32, 0x06, 0x70,
	0x06, 0x03, 0x5a, 0xf7, 0x47, 0x1e, 0xf3, 0x50, 0xa5, 0x37, 0xf2, 0x3b, 0x75, 0xbe, 0x71, 0xfe,
	0xb1, 0x79, 0xab, 0xe7, 0x79, 0xbd, 0x3e, 0xb9, 0xcf, 0xcf, 0xde, 0x8c, 0xbb, 0xf7, 0x99, 0x3b,
	0x20, 0x94, 0xd9, 0x03, 0x5f, 0x88, 0x5b, 0xff, 0x64, 0x20, 0xdf, 0x20, 0xe7, 0x6e, 0x87, 0xa0,
	0x55, 0xc8, 0x34, 0x1b, 0xd8, 0xa8, 0x19, 0x7b, 0xa5, 0x56, 0xa6, 0xd9, 0x40, 0x08, 0x72, 0x43,
	0x7b, 0x40, 0x70, 0x96, 0xef, 0xf0, 0x6f, 0x54, 0x83, 0xb2, 0x43, 0x68, 0x67, 0xe4, 0xfa, 0xcc,
	0xf5, 0x86, 0x38, 0xc7, 0x8f, 0xd4, 0x2d, 0x54, 0x85, 0x3c, 0x65, 0x36, 0x1b, 0x53, 0xbc, 0xcc,
	0x0f, 0xe5, 0x2a, 0xd8, 0x1f, 0x53, 0x32, 0x6a, 0x36, 0x70, 0x5e, 0xec, 0x8b, 0x15, 0xba, 0x09,
	0x25, 0x7f, 0xe4, 0xfd, 0x4c, 0x3a, 0xac, 0xd9, 0xc0, 0x05, 0x7e, 0x34, 0xd9, 0x40, 0x18, 0x0a,
	0x03, 0xcf, 0x21, 0xfd, 0x66, 0x03, 0x17, 0xf9, 0x59, 0xb8, 0x44, 0x0f, 0x01, 0x3a, 0x23, 0x62,
	0x33, 0xe2, 0xb4, 0x6d, 0x86, 0x4b, 0x35, 0x63, 0xaf, 0xbc, 0x6f, 0xd6, 0x45, 0xb8, 0xf5, 0x30,
	0xdc, 0xfa, 0xf7, 0x61, 0xb8, 0xad, 0x92, 0x94, 0x3e, 0x64, 0xe8, 0x08, 0xd6, 0xfa, 0x36, 0x65,
	0xed, 0xb1, 0xef, 0x84, 0xfa, 0x30, 0x57, 0x7f, 0x25, 0x50, 0x79, 0x26, 0x34, 0x0e, 0x19, 0xfa,
	0x0c, 0xc0, 0xb1, 0x99, 0xdd, 0xe6, 0x70, 0x70, 0x99, 0xab, 0x6f, 0xd5, 0x55, 0xee, 0xeb, 0x0d,
	0x9b, 0xd9, 0x27, 0xc1, 0x71, 0xab, 0xe4, 0x84, 0x9f, 0xd6, 0x5f, 0x06, 0x14, 0x1f, 0x0d, 0x1d,
	0xdf, 0x73, 0x87, 0x2c, 0x60, 0xd8, 0xb7, 0xd9, 0x99, 0xe4, 0x9c, 0x7f, 0x07, 0x3c, 0x75, 0xbd,
	0xd1, 0xc0, 0x66, 0x38, 0x23, 0x78, 0x12, 0x2b, 0x74, 0x00, 0x79, 0xee, 0x8b, 0xe2, 0x6c, 0x2d,
	0xbb, 0x57, 0xde, 0xb7, 0xe2, 0xce, 0x42, 0x9b, 0x75, 0xee, 0x86, 0x3e, 0x1a, 0xb2, 0xd1, 0x45,
	0x4b, 0x6a, 0x98, 0x0f, 0xa1, 0xac, 0x6c, 0xa3, 0x1b, 0x90, 0xfd, 0x85, 0x5c, 0x48, 0xaf, 0xc1,
	0x27, 0xda, 0x84, 0xe5, 0x73, 0xbb, 0x3f, 0x26, 0xd2, 0xa7, 0x58, 0x1c, 0x64, 0xbe, 0x30, 0xac,
	0xdf, 0x0c, 0x28, 0x45, 0x81, 0x44, 0x29, 0x61, 0x28, 0x29, 0x21, 0xd2, 0x26, 0x13, 0xa5, 0x4d,
	0x15, 0xf2, 0x8e, 0x37, 0xb0, 0xdd, 0xa1, 0x4c, 0x1c, 0xb9, 0x42, 0xdf, 0xc0, 0xfa, 0x84, 0xb1,
	0x76, 0xd7, 0x25, 0x7d, 0x87, 0xe2, 0x1c, 0x8f, 0xe5, 0x66, 0x0a, 0x71, 0x8f, 0x03, 0xa1, 0xd6,
	0x9a, 0x13, 0x5b, 0x53, 0xeb, 0x2d, 0xac, 0xc6, 0x45, 0x2e, 0x1b, 0x51, 0x80, 0x9f, 0x5d, 0xf8,
	0x51, 0x4a, 0x07, 0xdf, 0xe8, 0x36, 0xac, 0x38, 0xa4, 0x6b, 0x8f, 0xfb, 0xac, 0x2d, 0x34, 0x44,
	0x52, 0x57, 0xe4, 0xe6, 0xf3, 0x60, 0xcf, 0xfa, 0x37, 0x0b, 0x65, 0x51, 0x26, 0x82, 0x88, 0xb4,
	0x5a, 0xc9, 0xa4, 0xd7, 0x4a, 0x36, 0xb1, 0x56, 0x24, 0x55, 0xb9, 0x18, 0x55, 0x18, 0x0a, 0xe7,
	0x64, 0x44, 0x03, 0x2d, 0x51, 0x44, 0xe1, 0x12, 0x7d, 0x0a, 0x25, 0x22, 0x6f, 0x9a, 0xe2, 0x3c,
	0x27, 0xaf, 0x9a, 0x9c, 0x08, 0xad, 0x89, 0x20, 0xfa, 0x5c, 0x24, 0xab, 0xc8, 0x01, 0x5c, 0xe0,
	0x6a, 0xa9, 0xc9, 0xaa, 0x88, 0x06, 0xc5, 0xe9, 0xd2, 0x27, 0x5e, 0xcf, 0xed, 0xd8, 0x7d, 0x5e,
	0x80, 0xc5, 0xd6, 0x64, 0x03, 0xed, 0x02, 0xb8, 0xf4, 0xd8, 0x1b, 0xf8, 0xde, 0x78, 0xe8, 0xf0,
	0x12, 0x2c, 0xb6, 0x94, 0x9d, 0x80, 0x80, 0xe3, 0x33, 0xb7, 0xef, 0x48, 0xbf, 0x50, 0xcb, 0x06,
	0x04, 0x28, 0x5b, 0x5a, 0x11, 0x97, 0x17, 0x2c, 0xe2, 0xca, 0x55, 0x8b, 0x78, 0xd2, 0x93, 0x56,
	0x62, 0x3d, 0x09, 0x41, 0xae, 0xd9, 0xf1, 0x86, 0x78, 0x55, 0xdc, 0x66, 0xf0, 0x6d, 0xfd, 0x6d,
	0xc0, 0x8a, 0xcc, 0x00, 0xc2, 0x46, 0x6e, 0x47, 0xed, 0x68, 0x46, 0x4c, 0xdb, 0x84, 0xa2, 0xc3,
	0x05, 0xa3, 0xb2, 0x88, 0xd6, 0xe8, 0x08, 0x0a, 0x03, 0xa1, 0x2e, 0xcb, 0x78, 0x4f, 0xbb, 0x06,
	0xd5, 0x43, 0x5d, 0xfe, 0x8a, 0x62, 0x0e, 0x15, 0xcd, 0x03, 0xa8, 0xa8, 0x07, 0xf3, 0x92, 0x7f,
	0x59, 0x2d, 0xe7, 0x8b, 0x49, 0x10, 0x94, 0xda, 0x3d, 0xf2, 0x4e, 0x41, 0x98, 0x50, 0x0c, 0x73,
	0x4b, 0x66, 0x75, 0xb4, 0x0e, 0x52, 0xd7, 0xb7, 0x2f, 0xfa, 0x9e, 0xed, 0xf0, 0x9c, 0xae, 0xb4,
	0xc2, 0xa5, 0xe5, 0x03, 0x3e, 0xe6, 0xb7, 0xa7, 0xd4, 0x51, 0x8b, 0xbc, 0x1d, 0x13, 0xca, 0x52,
	0x51, 0x7c, 0x09, 0x15, 0xe1, 0x55, 0xf6, 0xd9, 0x0c, 0xbf, 0xe1, 0xed, 0x44, 0xce, 0xb8, 0xbd,
	0xb2, 0x33, 0x59, 0x58, 0xaf, 0x60, 0x3b, 0xc1, 0x23, 0xf5, 0xbd, 0x21, 0x25, 0x53, 0xa6, 0x8d,
	0x2b, 0x99, 0x7e, 0x06, 0xff, 0xfb, 0x9a, 0xb0, 0x2b, 0x44, 0x72, 0x27, 0xe8, 0x32, 0x91, 0x74,
	0x44, 0x6a, 0x7c, 0xd3, 0x7a, 0x0e, 0x55, 0xdd, 0xec, 0xb5, 0xc0, 0xed, 0xc0, 0xff, 0xe3, 0x76,
	0x5f, 0xb8, 0xec, 0xec, 0xa9, 0x3d, 0x20, 0xf3, 0x60, 0x7f, 0x08, 0xeb, 0xaa, 0xdb, 0xb6, 0xd2,
	0xe4, 0xd6, 0x14, 0x07, 0x81, 0x29, 0xeb, 0x35, 0xec, 0xa6, 0x39, 0xb9, 0x96, 0x20, 0x5e, 0x02,
	0x6e, 0x90, 0x3e, 0xb9, 0x52, 0x02, 0x5d, 0x8e, 0xf6, 0x1d, 0xd8, 0x4e, 0xb0, 0x2c, 0x40, 0x5b,
	0x7f, 0x18, 0x80, 0x45, 0xcb, 0xb8, 0x6e, 0xbf, 0x53, 0x7c, 0x64, 0xaf, 0xc4, 0xc7, 0x0e, 0x6c,
	0x27, 0xe0, 0x92, 0xa8, 0x1f, 0xe8, 0x99, 0x44, 0xe7, 0x40, 0xb6, 0x5e, 0xc1, 0xd6, 0x94, 0x86,
	0xbc, 0xb7, 0xaf, 0xc2, 0x68, 0xda, 0xf2, 0x09, 0x62, 0xf0, 0xde, 0x35, 0x03, 0x68, 0x45, 0x01,
	0x4a, 0xad, 0x97, 0x70, 0xe3, 0xd0, 0x71, 0xc4, 0xf9, 0x3c, 0xe6, 0xee, 0x41, 0x5e, 0xe8, 0xca,
	0x62, 0xdf, 0x4c, 0x72, 0xd2, 0x92, 0x32, 0xd6, 0x21, 0xac, 0x2b, 0x96, 0x25, 0xdc, 0x89, 0x09,
	0xe3, 0x12, 0x26, 0x1e, 0xc3, 0x8d, 0x28, 0xee, 0x79, 0xe0, 0x66, 0x74, 0xc5, 0x00, 0x8a, 0x62,
	0xe7, 0x9d, 0xa0, 0xfc, 0x00, 0x1b, 0xea, 0x8d, 0x5e, 0x2f, 0x55, 0x55, 0xd8, 0x8c, 0x1b, 0x97,
	0x99, 0xd2, 0x54, 0x70, 0xcf, 0x4b, 0x92, 0xe0, 0x41, 0x10, 0x06, 0x4c, 0x71, 0x86, 0x0f, 0xf4,
	0xc9, 0x86, 0xd5, 0x00, 0xa4, 0x9a, 0x92, 0x1c, 0xd4, 0xa1, 0x20, 0x44, 0xc2, 0xbc, 0x49, 0xc6,
	0x19, 0x0a, 0x59, 0x4d, 0xd8, 0x50, 0xab, 0x71, 0x91, 0x3b, 0xa9, 0xc2, 0x66, 0xdc, 0x94, 0x8c,
	0xd9, 0x81, 0xea, 0x69, 0x08, 0xf4, 0x94, 0xff, 0x3f, 0x59, 0xc0, 0x8b, 0xf2, 0x97, 0x27, 0xab,
	0xfe, 0xe5, 0xb1, 0xb6, 0x61, 0x6b, 0xca, 0x8b, 0x04, 0xf0, 0x2b, 0x6c, 0x44, 0x4c, 0x3d, 0xf1,
	0x7a, 0x8b, 0x78, 0x7f, 0x00, 0xcb, 0xd4, 0x1d, 0x76, 0x88, 0xec, 0x1e, 0xb3, 0x9e, 0x3f, 0x42,
	0x30, 0x60, 0x25, 0xee, 0x5c, 0x82, 0x3a, 0x51, 0x3b, 0x80, 0x78, 0x61, 0x2c, 0x42, 0xfe, 0x6b,
	0xc0, 0xd3, 0xe6, 0x64, 0x4e, 0x1c, 0xc1, 0x6a, 0xd8, 0x51, 0xe4, 0x73, 0x48, 0xd4, 0xc7, 0xce,
	0x8c, 0xe7, 0x50, 0xd4, 0x3d, 0xc5, 0xd2, 0xfa, 0xdd, 0x00, 0xfc, 0xad, 0x47, 0x59, 0xec, 0x41,
	0xb3, 0x08, 0x93, 0x2a, 0x28, 0x6e, 0x4c, 0x52, 0x9a, 0x02, 0x4a, 0xf8, 0x8b, 0x40, 0xf1, 0x65,
	0xd0, 0x94, 0x13, 0x30, 0x89, 0xa8, 0xf7, 0xff, 0x2c, 0x43, 0xae, 0x71, 0x72, 0x72, 0x8a, 0xba,
	0xb0, 0x3e, 0xf5, 0x32, 0x41, 0x77, 0xe3, 0x6e, 0xd2, 0x1e, 0x4b, 0xe6, 0x07, 0x73, 0xe5, 0xe4,
	0x7d, 0x2e, 0xa1, 0x1f, 0x61, 0x35, 0xde, 0xd3, 0xd1, 0xed, 0xb8, 0x72, 0xe2, 0x23, 0xc6, 0xbc,
	0x33, 0x5b, 0x28, 0x32, 0x3f, 0xd6, 0x87, 0x4c, 0x38, 0xf1, 0xd1, 0x47, 0xb3, 0x2c, 0x68, 0x8f,
	0x0f, 0xf3, 0xde, 0xe5, 0x84, 0x23, 0xb7, 0x5d, 0x58, 0x9f, 0x1a, 0xd7, 0x3a, 0x7b, 0x69, 0x2f,
	0x05, 0x9d, 0xbd, 0xf4, 0xb9, 0xcf, 0xfd, 0x4c, 0x0d, 0x58, 0xdd, 0x4f, 0xda, 0xcb, 0x40, 0xf7,
	0x93, 0x3e, 0xa9, 0x97, 0xd0, 0x4f, 0xb0, 0xa6, 0x4d, 0x5e, 0x34, 0xf3, 0x06, 0xc2, 0xaa, 0x34,
	0xdf, 0x9f, 0x23, 0x15, 0x79, 0x78, 0x0a, 0xa5, 0x68, 0x4c, 0xa2, 0xdd, 0xb8, 0x96, 0x3e, 0x99,
	0xcd, 0x5b, 0xa9, 0xe7, 0xaa, 0xbd, 0xc8, 0x99, 0x6e, 0x4f, 0x1f, 0xa6, 0xba, 0xbd, 0xa9, 0x21,
	0x69, 0x2d, 0xa1, 0x17, 0x50, 0x51, 0x09, 0x42, 0xef, 0xa5, 0x93, 0x17, 0x5a, 0xb5, 0x66, 0x89,
	0x44, 0x86, 0xbf, 0x03, 0x98, 0x4c, 0x24, 0x94, 0x86, 0x24, 0x22, 0xb4, 0x96, 0x2e, 0xa0, 0x62,
	0x55, 0x93, 0x46, 0xc7, 0x9a, 0x30, 0xba, 0x74, 0xac, 0x89, 0x23, 0x89, 0xa7, 0x81, 0x36, 0x2e,
	0xf4, 0x34, 0x48, 0x9e, 0x59, 0x7a, 0x1a, 0xa4, 0xcd, 0x1c, 0x0e, 0x5d, 0x6d, 0xfc, 0x3a, 0xf4,
	0x84, 0x89, 0xa4, 0x43, 0x4f, 0x9c, 0x1b, 0x4b, 0xa8, 0xa3, 0xbc, 0xa1, 0xc2, 0xbf, 0xc7, 0xa9,
	0xc9, 0x19, 0x9b, 0x2c, 0xe6, 0xdd, 0x79, 0x62, 0x6a, 0x39, 0x4e, 0xb5, 0x56, 0xbd, 0x1c, 0xd3,
	0xe6, 0x81, 0x5e, 0x8e, 0xa9, 0x3d, 0xda, 0x5a, 0x7a, 0x93, 0xe7, 0x93, 0xf3, 0x93, 0xff, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x7b, 0x57, 0xdb, 0x34, 0x56, 0x15, 0x00, 0x00,
}
