// Code generated by go-swagger; DO NOT EDIT.

package logs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/cloustone/pandas/models"
)

// GetDeviceLogHandlerFunc turns a function with the right signature into a get device log handler
type GetDeviceLogHandlerFunc func(GetDeviceLogParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDeviceLogHandlerFunc) Handle(params GetDeviceLogParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetDeviceLogHandler interface for that can handle valid get device log params
type GetDeviceLogHandler interface {
	Handle(GetDeviceLogParams, *models.Principal) middleware.Responder
}

// NewGetDeviceLog creates a new http.Handler for the get device log operation
func NewGetDeviceLog(ctx *middleware.Context, handler GetDeviceLogHandler) *GetDeviceLog {
	return &GetDeviceLog{Context: ctx, Handler: handler}
}

/*GetDeviceLog swagger:route GET /logs/devices/{deviceId} Logs getDeviceLog

get specified device's log

*/
type GetDeviceLog struct {
	Context *middleware.Context
	Handler GetDeviceLogHandler
}

func (o *GetDeviceLog) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDeviceLogParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
