// Code generated by go-swagger; DO NOT EDIT.

package rulechain

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewSaveRuleChainMetadataParams creates a new SaveRuleChainMetadataParams object
// with the default values initialized.
func NewSaveRuleChainMetadataParams() *SaveRuleChainMetadataParams {
	var ()
	return &SaveRuleChainMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSaveRuleChainMetadataParamsWithTimeout creates a new SaveRuleChainMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSaveRuleChainMetadataParamsWithTimeout(timeout time.Duration) *SaveRuleChainMetadataParams {
	var ()
	return &SaveRuleChainMetadataParams{

		timeout: timeout,
	}
}

// NewSaveRuleChainMetadataParamsWithContext creates a new SaveRuleChainMetadataParams object
// with the default values initialized, and the ability to set a context for a request
func NewSaveRuleChainMetadataParamsWithContext(ctx context.Context) *SaveRuleChainMetadataParams {
	var ()
	return &SaveRuleChainMetadataParams{

		Context: ctx,
	}
}

// NewSaveRuleChainMetadataParamsWithHTTPClient creates a new SaveRuleChainMetadataParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSaveRuleChainMetadataParamsWithHTTPClient(client *http.Client) *SaveRuleChainMetadataParams {
	var ()
	return &SaveRuleChainMetadataParams{
		HTTPClient: client,
	}
}

/*SaveRuleChainMetadataParams contains all the parameters to send to the API endpoint
for the save rule chain metadata operation typically these are written to a http.Request
*/
type SaveRuleChainMetadataParams struct {

	/*Metadata
	  meta data

	*/
	Metadata string
	/*RuleChainID
	  rule chain identifier

	*/
	RuleChainID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the save rule chain metadata params
func (o *SaveRuleChainMetadataParams) WithTimeout(timeout time.Duration) *SaveRuleChainMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the save rule chain metadata params
func (o *SaveRuleChainMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the save rule chain metadata params
func (o *SaveRuleChainMetadataParams) WithContext(ctx context.Context) *SaveRuleChainMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the save rule chain metadata params
func (o *SaveRuleChainMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the save rule chain metadata params
func (o *SaveRuleChainMetadataParams) WithHTTPClient(client *http.Client) *SaveRuleChainMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the save rule chain metadata params
func (o *SaveRuleChainMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMetadata adds the metadata to the save rule chain metadata params
func (o *SaveRuleChainMetadataParams) WithMetadata(metadata string) *SaveRuleChainMetadataParams {
	o.SetMetadata(metadata)
	return o
}

// SetMetadata adds the metadata to the save rule chain metadata params
func (o *SaveRuleChainMetadataParams) SetMetadata(metadata string) {
	o.Metadata = metadata
}

// WithRuleChainID adds the ruleChainID to the save rule chain metadata params
func (o *SaveRuleChainMetadataParams) WithRuleChainID(ruleChainID string) *SaveRuleChainMetadataParams {
	o.SetRuleChainID(ruleChainID)
	return o
}

// SetRuleChainID adds the ruleChainId to the save rule chain metadata params
func (o *SaveRuleChainMetadataParams) SetRuleChainID(ruleChainID string) {
	o.RuleChainID = ruleChainID
}

// WriteToRequest writes these params to a swagger request
func (o *SaveRuleChainMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Metadata); err != nil {
		return err
	}

	// path param ruleChainId
	if err := r.SetPathParam("ruleChainId", o.RuleChainID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
