// Code generated by go-swagger; DO NOT EDIT.

package rulechain

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// SaveRuleChainReader is a Reader for the SaveRuleChain structure.
type SaveRuleChainReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SaveRuleChainReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSaveRuleChainOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewSaveRuleChainNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSaveRuleChainInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSaveRuleChainOK creates a SaveRuleChainOK with default headers values
func NewSaveRuleChainOK() *SaveRuleChainOK {
	return &SaveRuleChainOK{}
}

/*SaveRuleChainOK handles this case with default header values.

Successfully operation
*/
type SaveRuleChainOK struct {
}

func (o *SaveRuleChainOK) Error() string {
	return fmt.Sprintf("[POST /rulechains/{ruleChainId}][%d] saveRuleChainOK ", 200)
}

func (o *SaveRuleChainOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSaveRuleChainNotFound creates a SaveRuleChainNotFound with default headers values
func NewSaveRuleChainNotFound() *SaveRuleChainNotFound {
	return &SaveRuleChainNotFound{}
}

/*SaveRuleChainNotFound handles this case with default header values.

Rule chain not found
*/
type SaveRuleChainNotFound struct {
}

func (o *SaveRuleChainNotFound) Error() string {
	return fmt.Sprintf("[POST /rulechains/{ruleChainId}][%d] saveRuleChainNotFound ", 404)
}

func (o *SaveRuleChainNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSaveRuleChainInternalServerError creates a SaveRuleChainInternalServerError with default headers values
func NewSaveRuleChainInternalServerError() *SaveRuleChainInternalServerError {
	return &SaveRuleChainInternalServerError{}
}

/*SaveRuleChainInternalServerError handles this case with default header values.

Server internal error
*/
type SaveRuleChainInternalServerError struct {
}

func (o *SaveRuleChainInternalServerError) Error() string {
	return fmt.Sprintf("[POST /rulechains/{ruleChainId}][%d] saveRuleChainInternalServerError ", 500)
}

func (o *SaveRuleChainInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
