// Code generated by go-swagger; DO NOT EDIT.

package deployment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SetDeploymentStatusOKCode is the HTTP code returned for type SetDeploymentStatusOK
const SetDeploymentStatusOKCode int = 200

/*SetDeploymentStatusOK Successfully operation

swagger:response setDeploymentStatusOK
*/
type SetDeploymentStatusOK struct {
}

// NewSetDeploymentStatusOK creates SetDeploymentStatusOK with default headers values
func NewSetDeploymentStatusOK() *SetDeploymentStatusOK {

	return &SetDeploymentStatusOK{}
}

// WriteResponse to the client
func (o *SetDeploymentStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// SetDeploymentStatusBadRequestCode is the HTTP code returned for type SetDeploymentStatusBadRequest
const SetDeploymentStatusBadRequestCode int = 400

/*SetDeploymentStatusBadRequest Invalid deployment Id

swagger:response setDeploymentStatusBadRequest
*/
type SetDeploymentStatusBadRequest struct {
}

// NewSetDeploymentStatusBadRequest creates SetDeploymentStatusBadRequest with default headers values
func NewSetDeploymentStatusBadRequest() *SetDeploymentStatusBadRequest {

	return &SetDeploymentStatusBadRequest{}
}

// WriteResponse to the client
func (o *SetDeploymentStatusBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// SetDeploymentStatusNotFoundCode is the HTTP code returned for type SetDeploymentStatusNotFound
const SetDeploymentStatusNotFoundCode int = 404

/*SetDeploymentStatusNotFound Deployment not found

swagger:response setDeploymentStatusNotFound
*/
type SetDeploymentStatusNotFound struct {
}

// NewSetDeploymentStatusNotFound creates SetDeploymentStatusNotFound with default headers values
func NewSetDeploymentStatusNotFound() *SetDeploymentStatusNotFound {

	return &SetDeploymentStatusNotFound{}
}

// WriteResponse to the client
func (o *SetDeploymentStatusNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// SetDeploymentStatusMethodNotAllowedCode is the HTTP code returned for type SetDeploymentStatusMethodNotAllowed
const SetDeploymentStatusMethodNotAllowedCode int = 405

/*SetDeploymentStatusMethodNotAllowed Deployment exception

swagger:response setDeploymentStatusMethodNotAllowed
*/
type SetDeploymentStatusMethodNotAllowed struct {
}

// NewSetDeploymentStatusMethodNotAllowed creates SetDeploymentStatusMethodNotAllowed with default headers values
func NewSetDeploymentStatusMethodNotAllowed() *SetDeploymentStatusMethodNotAllowed {

	return &SetDeploymentStatusMethodNotAllowed{}
}

// WriteResponse to the client
func (o *SetDeploymentStatusMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
