// Code generated by go-swagger; DO NOT EDIT.

package deployment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/cloustone/pandas/models"
)

// SetDeploymentStatusHandlerFunc turns a function with the right signature into a set deployment status handler
type SetDeploymentStatusHandlerFunc func(SetDeploymentStatusParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SetDeploymentStatusHandlerFunc) Handle(params SetDeploymentStatusParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SetDeploymentStatusHandler interface for that can handle valid set deployment status params
type SetDeploymentStatusHandler interface {
	Handle(SetDeploymentStatusParams, *models.Principal) middleware.Responder
}

// NewSetDeploymentStatus creates a new http.Handler for the set deployment status operation
func NewSetDeploymentStatus(ctx *middleware.Context, handler SetDeploymentStatusHandler) *SetDeploymentStatus {
	return &SetDeploymentStatus{Context: ctx, Handler: handler}
}

/*SetDeploymentStatus swagger:route PATCH /deployments/{deploymentId} Deployment setDeploymentStatus

update specified deployment

*/
type SetDeploymentStatus struct {
	Context *middleware.Context
	Handler SetDeploymentStatusHandler
}

func (o *SetDeploymentStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSetDeploymentStatusParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
