// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/cloustone/pandas/models"
)

// SendDataToDeviceHandlerFunc turns a function with the right signature into a send data to device handler
type SendDataToDeviceHandlerFunc func(SendDataToDeviceParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SendDataToDeviceHandlerFunc) Handle(params SendDataToDeviceParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SendDataToDeviceHandler interface for that can handle valid send data to device params
type SendDataToDeviceHandler interface {
	Handle(SendDataToDeviceParams, *models.Principal) middleware.Responder
}

// NewSendDataToDevice creates a new http.Handler for the send data to device operation
func NewSendDataToDevice(ctx *middleware.Context, handler SendDataToDeviceHandler) *SendDataToDevice {
	return &SendDataToDevice{Context: ctx, Handler: handler}
}

/*SendDataToDevice swagger:route POST /devices/{deviceId} Device sendDataToDevice

send data to device

send data to device

*/
type SendDataToDevice struct {
	Context *middleware.Context
	Handler SendDataToDeviceHandler
}

func (o *SendDataToDevice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSendDataToDeviceParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
