// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// SendDataToDeviceReader is a Reader for the SendDataToDevice structure.
type SendDataToDeviceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SendDataToDeviceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSendDataToDeviceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSendDataToDeviceBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSendDataToDeviceInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSendDataToDeviceOK creates a SendDataToDeviceOK with default headers values
func NewSendDataToDeviceOK() *SendDataToDeviceOK {
	return &SendDataToDeviceOK{}
}

/*SendDataToDeviceOK handles this case with default header values.

Successful operation
*/
type SendDataToDeviceOK struct {
}

func (o *SendDataToDeviceOK) Error() string {
	return fmt.Sprintf("[POST /devices/{deviceId}][%d] sendDataToDeviceOK ", 200)
}

func (o *SendDataToDeviceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSendDataToDeviceBadRequest creates a SendDataToDeviceBadRequest with default headers values
func NewSendDataToDeviceBadRequest() *SendDataToDeviceBadRequest {
	return &SendDataToDeviceBadRequest{}
}

/*SendDataToDeviceBadRequest handles this case with default header values.

Bad request
*/
type SendDataToDeviceBadRequest struct {
}

func (o *SendDataToDeviceBadRequest) Error() string {
	return fmt.Sprintf("[POST /devices/{deviceId}][%d] sendDataToDeviceBadRequest ", 400)
}

func (o *SendDataToDeviceBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSendDataToDeviceInternalServerError creates a SendDataToDeviceInternalServerError with default headers values
func NewSendDataToDeviceInternalServerError() *SendDataToDeviceInternalServerError {
	return &SendDataToDeviceInternalServerError{}
}

/*SendDataToDeviceInternalServerError handles this case with default header values.

Server internal error
*/
type SendDataToDeviceInternalServerError struct {
}

func (o *SendDataToDeviceInternalServerError) Error() string {
	return fmt.Sprintf("[POST /devices/{deviceId}][%d] sendDataToDeviceInternalServerError ", 500)
}

func (o *SendDataToDeviceInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
