// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewChangeCurrentUserPasswordParams creates a new ChangeCurrentUserPasswordParams object
// no default values defined in spec.
func NewChangeCurrentUserPasswordParams() ChangeCurrentUserPasswordParams {

	return ChangeCurrentUserPasswordParams{}
}

// ChangeCurrentUserPasswordParams contains all the bound params for the change current user password operation
// typically these are obtained from a http.Request
//
// swagger:parameters ChangeCurrentUserPassword
type ChangeCurrentUserPasswordParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Updated user password
	  Required: true
	  In: body
	*/
	User ChangeCurrentUserPasswordBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewChangeCurrentUserPasswordParams() beforehand.
func (o *ChangeCurrentUserPasswordParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body ChangeCurrentUserPasswordBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("user", "body"))
			} else {
				res = append(res, errors.NewParseError("user", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.User = body
			}
		}
	} else {
		res = append(res, errors.Required("user", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
