// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewChangeUserPasswordParams creates a new ChangeUserPasswordParams object
// with the default values initialized.
func NewChangeUserPasswordParams() *ChangeUserPasswordParams {
	var ()
	return &ChangeUserPasswordParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangeUserPasswordParamsWithTimeout creates a new ChangeUserPasswordParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangeUserPasswordParamsWithTimeout(timeout time.Duration) *ChangeUserPasswordParams {
	var ()
	return &ChangeUserPasswordParams{

		timeout: timeout,
	}
}

// NewChangeUserPasswordParamsWithContext creates a new ChangeUserPasswordParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangeUserPasswordParamsWithContext(ctx context.Context) *ChangeUserPasswordParams {
	var ()
	return &ChangeUserPasswordParams{

		Context: ctx,
	}
}

// NewChangeUserPasswordParamsWithHTTPClient creates a new ChangeUserPasswordParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangeUserPasswordParamsWithHTTPClient(client *http.Client) *ChangeUserPasswordParams {
	var ()
	return &ChangeUserPasswordParams{
		HTTPClient: client,
	}
}

/*ChangeUserPasswordParams contains all the parameters to send to the API endpoint
for the change user password operation typically these are written to a http.Request
*/
type ChangeUserPasswordParams struct {

	/*User
	  Updated user password

	*/
	User ChangeUserPasswordBody
	/*UserID
	  name that need to be updated

	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the change user password params
func (o *ChangeUserPasswordParams) WithTimeout(timeout time.Duration) *ChangeUserPasswordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the change user password params
func (o *ChangeUserPasswordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the change user password params
func (o *ChangeUserPasswordParams) WithContext(ctx context.Context) *ChangeUserPasswordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the change user password params
func (o *ChangeUserPasswordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the change user password params
func (o *ChangeUserPasswordParams) WithHTTPClient(client *http.Client) *ChangeUserPasswordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the change user password params
func (o *ChangeUserPasswordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUser adds the user to the change user password params
func (o *ChangeUserPasswordParams) WithUser(user ChangeUserPasswordBody) *ChangeUserPasswordParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the change user password params
func (o *ChangeUserPasswordParams) SetUser(user ChangeUserPasswordBody) {
	o.User = user
}

// WithUserID adds the userID to the change user password params
func (o *ChangeUserPasswordParams) WithUserID(userID string) *ChangeUserPasswordParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the change user password params
func (o *ChangeUserPasswordParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeUserPasswordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.User); err != nil {
		return err
	}

	// path param userId
	if err := r.SetPathParam("userId", o.UserID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
