// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLoginUserParams creates a new LoginUserParams object
// with the default values initialized.
func NewLoginUserParams() *LoginUserParams {
	var ()
	return &LoginUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLoginUserParamsWithTimeout creates a new LoginUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLoginUserParamsWithTimeout(timeout time.Duration) *LoginUserParams {
	var ()
	return &LoginUserParams{

		timeout: timeout,
	}
}

// NewLoginUserParamsWithContext creates a new LoginUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewLoginUserParamsWithContext(ctx context.Context) *LoginUserParams {
	var ()
	return &LoginUserParams{

		Context: ctx,
	}
}

// NewLoginUserParamsWithHTTPClient creates a new LoginUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLoginUserParamsWithHTTPClient(client *http.Client) *LoginUserParams {
	var ()
	return &LoginUserParams{
		HTTPClient: client,
	}
}

/*LoginUserParams contains all the parameters to send to the API endpoint
for the login user operation typically these are written to a http.Request
*/
type LoginUserParams struct {

	/*GrantType*/
	GrantType string
	/*Password
	  The password for login in clear text

	*/
	Password string
	/*Username
	  The user name for login

	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the login user params
func (o *LoginUserParams) WithTimeout(timeout time.Duration) *LoginUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the login user params
func (o *LoginUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the login user params
func (o *LoginUserParams) WithContext(ctx context.Context) *LoginUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the login user params
func (o *LoginUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the login user params
func (o *LoginUserParams) WithHTTPClient(client *http.Client) *LoginUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the login user params
func (o *LoginUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGrantType adds the grantType to the login user params
func (o *LoginUserParams) WithGrantType(grantType string) *LoginUserParams {
	o.SetGrantType(grantType)
	return o
}

// SetGrantType adds the grantType to the login user params
func (o *LoginUserParams) SetGrantType(grantType string) {
	o.GrantType = grantType
}

// WithPassword adds the password to the login user params
func (o *LoginUserParams) WithPassword(password string) *LoginUserParams {
	o.SetPassword(password)
	return o
}

// SetPassword adds the password to the login user params
func (o *LoginUserParams) SetPassword(password string) {
	o.Password = password
}

// WithUsername adds the username to the login user params
func (o *LoginUserParams) WithUsername(username string) *LoginUserParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the login user params
func (o *LoginUserParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *LoginUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param grant_type
	frGrantType := o.GrantType
	fGrantType := frGrantType
	if fGrantType != "" {
		if err := r.SetFormParam("grant_type", fGrantType); err != nil {
			return err
		}
	}

	// form param password
	frPassword := o.Password
	fPassword := frPassword
	if fPassword != "" {
		if err := r.SetFormParam("password", fPassword); err != nil {
			return err
		}
	}

	// form param username
	frUsername := o.Username
	fUsername := frUsername
	if fUsername != "" {
		if err := r.SetFormParam("username", fUsername); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
