// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rulechain.proto

package grpc_rulechain_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RuleChain struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" bson:"name,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty" bson:"ID,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty" bson:"userID,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty" bson:"type,omitempty"`
	Domain               string   `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty" bson:"domain,omitempty"`
	Payload              []byte   `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty" bson:"payload,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty" bson:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuleChain) Reset()         { *m = RuleChain{} }
func (m *RuleChain) String() string { return proto.CompactTextString(m) }
func (*RuleChain) ProtoMessage()    {}
func (*RuleChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{0}
}
func (m *RuleChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuleChain.Unmarshal(m, b)
}
func (m *RuleChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuleChain.Marshal(b, m, deterministic)
}
func (dst *RuleChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuleChain.Merge(dst, src)
}
func (m *RuleChain) XXX_Size() int {
	return xxx_messageInfo_RuleChain.Size(m)
}
func (m *RuleChain) XXX_DiscardUnknown() {
	xxx_messageInfo_RuleChain.DiscardUnknown(m)
}

var xxx_messageInfo_RuleChain proto.InternalMessageInfo

func (m *RuleChain) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RuleChain) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *RuleChain) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RuleChain) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *RuleChain) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *RuleChain) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *RuleChain) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type CheckRuleChainRequest struct {
	RuleChain            *RuleChain `protobuf:"bytes,1,opt,name=rule_chain,json=ruleChain,proto3" json:"rule_chain,omitempty" bson:"rule_chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CheckRuleChainRequest) Reset()         { *m = CheckRuleChainRequest{} }
func (m *CheckRuleChainRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRuleChainRequest) ProtoMessage()    {}
func (*CheckRuleChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{1}
}
func (m *CheckRuleChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRuleChainRequest.Unmarshal(m, b)
}
func (m *CheckRuleChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRuleChainRequest.Marshal(b, m, deterministic)
}
func (dst *CheckRuleChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRuleChainRequest.Merge(dst, src)
}
func (m *CheckRuleChainRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRuleChainRequest.Size(m)
}
func (m *CheckRuleChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRuleChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRuleChainRequest proto.InternalMessageInfo

func (m *CheckRuleChainRequest) GetRuleChain() *RuleChain {
	if m != nil {
		return m.RuleChain
	}
	return nil
}

type CheckRuleChainResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty" bson:"valid,omitempty"`
	Reasons              []string `protobuf:"bytes,2,rep,name=reasons,proto3" json:"reasons,omitempty" bson:"reasons,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRuleChainResponse) Reset()         { *m = CheckRuleChainResponse{} }
func (m *CheckRuleChainResponse) String() string { return proto.CompactTextString(m) }
func (*CheckRuleChainResponse) ProtoMessage()    {}
func (*CheckRuleChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{2}
}
func (m *CheckRuleChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRuleChainResponse.Unmarshal(m, b)
}
func (m *CheckRuleChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRuleChainResponse.Marshal(b, m, deterministic)
}
func (dst *CheckRuleChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRuleChainResponse.Merge(dst, src)
}
func (m *CheckRuleChainResponse) XXX_Size() int {
	return xxx_messageInfo_CheckRuleChainResponse.Size(m)
}
func (m *CheckRuleChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRuleChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRuleChainResponse proto.InternalMessageInfo

func (m *CheckRuleChainResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *CheckRuleChainResponse) GetReasons() []string {
	if m != nil {
		return m.Reasons
	}
	return nil
}

type CreateRuleChainRequest struct {
	RuleChain            *RuleChain       `protobuf:"bytes,1,opt,name=rule_chain,json=ruleChain,proto3" json:"rule_chain,omitempty" bson:"rule_chain,omitempty"`
	Config               *RuleChainConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty" bson:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateRuleChainRequest) Reset()         { *m = CreateRuleChainRequest{} }
func (m *CreateRuleChainRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRuleChainRequest) ProtoMessage()    {}
func (*CreateRuleChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{3}
}
func (m *CreateRuleChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuleChainRequest.Unmarshal(m, b)
}
func (m *CreateRuleChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuleChainRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRuleChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuleChainRequest.Merge(dst, src)
}
func (m *CreateRuleChainRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRuleChainRequest.Size(m)
}
func (m *CreateRuleChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuleChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuleChainRequest proto.InternalMessageInfo

func (m *CreateRuleChainRequest) GetRuleChain() *RuleChain {
	if m != nil {
		return m.RuleChain
	}
	return nil
}

func (m *CreateRuleChainRequest) GetConfig() *RuleChainConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type RuleChainConfig struct {
	EndpointURL          string   `protobuf:"bytes,1,opt,name=endpointURL,proto3" json:"endpointURL,omitempty" bson:"endpointURL,omitempty"`
	Port                 string   `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty" bson:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuleChainConfig) Reset()         { *m = RuleChainConfig{} }
func (m *RuleChainConfig) String() string { return proto.CompactTextString(m) }
func (*RuleChainConfig) ProtoMessage()    {}
func (*RuleChainConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{4}
}
func (m *RuleChainConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuleChainConfig.Unmarshal(m, b)
}
func (m *RuleChainConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuleChainConfig.Marshal(b, m, deterministic)
}
func (dst *RuleChainConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuleChainConfig.Merge(dst, src)
}
func (m *RuleChainConfig) XXX_Size() int {
	return xxx_messageInfo_RuleChainConfig.Size(m)
}
func (m *RuleChainConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RuleChainConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RuleChainConfig proto.InternalMessageInfo

func (m *RuleChainConfig) GetEndpointURL() string {
	if m != nil {
		return m.EndpointURL
	}
	return ""
}

func (m *RuleChainConfig) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type CreateRuleChainResponse struct {
	Reasons              []string `protobuf:"bytes,1,rep,name=reasons,proto3" json:"reasons,omitempty" bson:"reasons,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRuleChainResponse) Reset()         { *m = CreateRuleChainResponse{} }
func (m *CreateRuleChainResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRuleChainResponse) ProtoMessage()    {}
func (*CreateRuleChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{5}
}
func (m *CreateRuleChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRuleChainResponse.Unmarshal(m, b)
}
func (m *CreateRuleChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRuleChainResponse.Marshal(b, m, deterministic)
}
func (dst *CreateRuleChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRuleChainResponse.Merge(dst, src)
}
func (m *CreateRuleChainResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRuleChainResponse.Size(m)
}
func (m *CreateRuleChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRuleChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRuleChainResponse proto.InternalMessageInfo

func (m *CreateRuleChainResponse) GetReasons() []string {
	if m != nil {
		return m.Reasons
	}
	return nil
}

// Delete RuleChain
type DeleteRuleChainRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty" bson:"userID,omitempty"`
	DomainID             string   `protobuf:"bytes,2,opt,name=domainID,proto3" json:"domainID,omitempty" bson:"domainID,omitempty"`
	RuleChainID          string   `protobuf:"bytes,3,opt,name=ruleChainID,proto3" json:"ruleChainID,omitempty" bson:"ruleChainID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRuleChainRequest) Reset()         { *m = DeleteRuleChainRequest{} }
func (m *DeleteRuleChainRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRuleChainRequest) ProtoMessage()    {}
func (*DeleteRuleChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{6}
}
func (m *DeleteRuleChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRuleChainRequest.Unmarshal(m, b)
}
func (m *DeleteRuleChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRuleChainRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRuleChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRuleChainRequest.Merge(dst, src)
}
func (m *DeleteRuleChainRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRuleChainRequest.Size(m)
}
func (m *DeleteRuleChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRuleChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRuleChainRequest proto.InternalMessageInfo

func (m *DeleteRuleChainRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *DeleteRuleChainRequest) GetDomainID() string {
	if m != nil {
		return m.DomainID
	}
	return ""
}

func (m *DeleteRuleChainRequest) GetRuleChainID() string {
	if m != nil {
		return m.RuleChainID
	}
	return ""
}

type DeleteRuleChainResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRuleChainResponse) Reset()         { *m = DeleteRuleChainResponse{} }
func (m *DeleteRuleChainResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRuleChainResponse) ProtoMessage()    {}
func (*DeleteRuleChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{7}
}
func (m *DeleteRuleChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRuleChainResponse.Unmarshal(m, b)
}
func (m *DeleteRuleChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRuleChainResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteRuleChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRuleChainResponse.Merge(dst, src)
}
func (m *DeleteRuleChainResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRuleChainResponse.Size(m)
}
func (m *DeleteRuleChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRuleChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRuleChainResponse proto.InternalMessageInfo

// Update RuleChain
type UpdateRuleChainRequest struct {
	RuleChain            *RuleChain `protobuf:"bytes,1,opt,name=ruleChain,proto3" json:"ruleChain,omitempty" bson:"ruleChain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateRuleChainRequest) Reset()         { *m = UpdateRuleChainRequest{} }
func (m *UpdateRuleChainRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRuleChainRequest) ProtoMessage()    {}
func (*UpdateRuleChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{8}
}
func (m *UpdateRuleChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRuleChainRequest.Unmarshal(m, b)
}
func (m *UpdateRuleChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRuleChainRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRuleChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRuleChainRequest.Merge(dst, src)
}
func (m *UpdateRuleChainRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRuleChainRequest.Size(m)
}
func (m *UpdateRuleChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRuleChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRuleChainRequest proto.InternalMessageInfo

func (m *UpdateRuleChainRequest) GetRuleChain() *RuleChain {
	if m != nil {
		return m.RuleChain
	}
	return nil
}

type UpdateRuleChainResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRuleChainResponse) Reset()         { *m = UpdateRuleChainResponse{} }
func (m *UpdateRuleChainResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateRuleChainResponse) ProtoMessage()    {}
func (*UpdateRuleChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{9}
}
func (m *UpdateRuleChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRuleChainResponse.Unmarshal(m, b)
}
func (m *UpdateRuleChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRuleChainResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateRuleChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRuleChainResponse.Merge(dst, src)
}
func (m *UpdateRuleChainResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateRuleChainResponse.Size(m)
}
func (m *UpdateRuleChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRuleChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRuleChainResponse proto.InternalMessageInfo

type GetRuleChainRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty" bson:"userID,omitempty"`
	Domain               string   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty" bson:"domain,omitempty"`
	RuleChainID          string   `protobuf:"bytes,3,opt,name=rule_chainID,json=ruleChainID,proto3" json:"rule_chainID,omitempty" bson:"rule_chainID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRuleChainRequest) Reset()         { *m = GetRuleChainRequest{} }
func (m *GetRuleChainRequest) String() string { return proto.CompactTextString(m) }
func (*GetRuleChainRequest) ProtoMessage()    {}
func (*GetRuleChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{10}
}
func (m *GetRuleChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRuleChainRequest.Unmarshal(m, b)
}
func (m *GetRuleChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRuleChainRequest.Marshal(b, m, deterministic)
}
func (dst *GetRuleChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRuleChainRequest.Merge(dst, src)
}
func (m *GetRuleChainRequest) XXX_Size() int {
	return xxx_messageInfo_GetRuleChainRequest.Size(m)
}
func (m *GetRuleChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRuleChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRuleChainRequest proto.InternalMessageInfo

func (m *GetRuleChainRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetRuleChainRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *GetRuleChainRequest) GetRuleChainID() string {
	if m != nil {
		return m.RuleChainID
	}
	return ""
}

type GetRuleChainResponse struct {
	RuleChain            *RuleChain `protobuf:"bytes,1,opt,name=rule_chain,json=ruleChain,proto3" json:"rule_chain,omitempty" bson:"rule_chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetRuleChainResponse) Reset()         { *m = GetRuleChainResponse{} }
func (m *GetRuleChainResponse) String() string { return proto.CompactTextString(m) }
func (*GetRuleChainResponse) ProtoMessage()    {}
func (*GetRuleChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{11}
}
func (m *GetRuleChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRuleChainResponse.Unmarshal(m, b)
}
func (m *GetRuleChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRuleChainResponse.Marshal(b, m, deterministic)
}
func (dst *GetRuleChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRuleChainResponse.Merge(dst, src)
}
func (m *GetRuleChainResponse) XXX_Size() int {
	return xxx_messageInfo_GetRuleChainResponse.Size(m)
}
func (m *GetRuleChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRuleChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRuleChainResponse proto.InternalMessageInfo

func (m *GetRuleChainResponse) GetRuleChain() *RuleChain {
	if m != nil {
		return m.RuleChain
	}
	return nil
}

type GetRuleChainsRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty" bson:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRuleChainsRequest) Reset()         { *m = GetRuleChainsRequest{} }
func (m *GetRuleChainsRequest) String() string { return proto.CompactTextString(m) }
func (*GetRuleChainsRequest) ProtoMessage()    {}
func (*GetRuleChainsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{12}
}
func (m *GetRuleChainsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRuleChainsRequest.Unmarshal(m, b)
}
func (m *GetRuleChainsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRuleChainsRequest.Marshal(b, m, deterministic)
}
func (dst *GetRuleChainsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRuleChainsRequest.Merge(dst, src)
}
func (m *GetRuleChainsRequest) XXX_Size() int {
	return xxx_messageInfo_GetRuleChainsRequest.Size(m)
}
func (m *GetRuleChainsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRuleChainsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRuleChainsRequest proto.InternalMessageInfo

func (m *GetRuleChainsRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetRuleChainsResponse struct {
	RuleChains           []*RuleChain `protobuf:"bytes,1,rep,name=rule_chains,json=ruleChains,proto3" json:"rule_chains,omitempty" bson:"rule_chains,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetRuleChainsResponse) Reset()         { *m = GetRuleChainsResponse{} }
func (m *GetRuleChainsResponse) String() string { return proto.CompactTextString(m) }
func (*GetRuleChainsResponse) ProtoMessage()    {}
func (*GetRuleChainsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{13}
}
func (m *GetRuleChainsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRuleChainsResponse.Unmarshal(m, b)
}
func (m *GetRuleChainsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRuleChainsResponse.Marshal(b, m, deterministic)
}
func (dst *GetRuleChainsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRuleChainsResponse.Merge(dst, src)
}
func (m *GetRuleChainsResponse) XXX_Size() int {
	return xxx_messageInfo_GetRuleChainsResponse.Size(m)
}
func (m *GetRuleChainsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRuleChainsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRuleChainsResponse proto.InternalMessageInfo

func (m *GetRuleChainsResponse) GetRuleChains() []*RuleChain {
	if m != nil {
		return m.RuleChains
	}
	return nil
}

type StartRuleChainRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty" bson:"userID,omitempty"`
	RuleChainID          string   `protobuf:"bytes,2,opt,name=rule_chainID,json=ruleChainID,proto3" json:"rule_chainID,omitempty" bson:"rule_chainID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRuleChainRequest) Reset()         { *m = StartRuleChainRequest{} }
func (m *StartRuleChainRequest) String() string { return proto.CompactTextString(m) }
func (*StartRuleChainRequest) ProtoMessage()    {}
func (*StartRuleChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{14}
}
func (m *StartRuleChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRuleChainRequest.Unmarshal(m, b)
}
func (m *StartRuleChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRuleChainRequest.Marshal(b, m, deterministic)
}
func (dst *StartRuleChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRuleChainRequest.Merge(dst, src)
}
func (m *StartRuleChainRequest) XXX_Size() int {
	return xxx_messageInfo_StartRuleChainRequest.Size(m)
}
func (m *StartRuleChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRuleChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRuleChainRequest proto.InternalMessageInfo

func (m *StartRuleChainRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *StartRuleChainRequest) GetRuleChainID() string {
	if m != nil {
		return m.RuleChainID
	}
	return ""
}

type StartRuleChainResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRuleChainResponse) Reset()         { *m = StartRuleChainResponse{} }
func (m *StartRuleChainResponse) String() string { return proto.CompactTextString(m) }
func (*StartRuleChainResponse) ProtoMessage()    {}
func (*StartRuleChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{15}
}
func (m *StartRuleChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRuleChainResponse.Unmarshal(m, b)
}
func (m *StartRuleChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRuleChainResponse.Marshal(b, m, deterministic)
}
func (dst *StartRuleChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRuleChainResponse.Merge(dst, src)
}
func (m *StartRuleChainResponse) XXX_Size() int {
	return xxx_messageInfo_StartRuleChainResponse.Size(m)
}
func (m *StartRuleChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRuleChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartRuleChainResponse proto.InternalMessageInfo

type StopRuleChainRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty" bson:"userID,omitempty"`
	RuleChainID          string   `protobuf:"bytes,2,opt,name=rule_chainID,json=ruleChainID,proto3" json:"rule_chainID,omitempty" bson:"rule_chainID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRuleChainRequest) Reset()         { *m = StopRuleChainRequest{} }
func (m *StopRuleChainRequest) String() string { return proto.CompactTextString(m) }
func (*StopRuleChainRequest) ProtoMessage()    {}
func (*StopRuleChainRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{16}
}
func (m *StopRuleChainRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRuleChainRequest.Unmarshal(m, b)
}
func (m *StopRuleChainRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRuleChainRequest.Marshal(b, m, deterministic)
}
func (dst *StopRuleChainRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRuleChainRequest.Merge(dst, src)
}
func (m *StopRuleChainRequest) XXX_Size() int {
	return xxx_messageInfo_StopRuleChainRequest.Size(m)
}
func (m *StopRuleChainRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRuleChainRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRuleChainRequest proto.InternalMessageInfo

func (m *StopRuleChainRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *StopRuleChainRequest) GetRuleChainID() string {
	if m != nil {
		return m.RuleChainID
	}
	return ""
}

type StopRuleChainResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRuleChainResponse) Reset()         { *m = StopRuleChainResponse{} }
func (m *StopRuleChainResponse) String() string { return proto.CompactTextString(m) }
func (*StopRuleChainResponse) ProtoMessage()    {}
func (*StopRuleChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{17}
}
func (m *StopRuleChainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRuleChainResponse.Unmarshal(m, b)
}
func (m *StopRuleChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRuleChainResponse.Marshal(b, m, deterministic)
}
func (dst *StopRuleChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRuleChainResponse.Merge(dst, src)
}
func (m *StopRuleChainResponse) XXX_Size() int {
	return xxx_messageInfo_StopRuleChainResponse.Size(m)
}
func (m *StopRuleChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRuleChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopRuleChainResponse proto.InternalMessageInfo

// Node Configs
type NodeConfig struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty" bson:"type,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty" bson:"category,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty" bson:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeConfig) Reset()         { *m = NodeConfig{} }
func (m *NodeConfig) String() string { return proto.CompactTextString(m) }
func (*NodeConfig) ProtoMessage()    {}
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{18}
}
func (m *NodeConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeConfig.Unmarshal(m, b)
}
func (m *NodeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeConfig.Marshal(b, m, deterministic)
}
func (dst *NodeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeConfig.Merge(dst, src)
}
func (m *NodeConfig) XXX_Size() int {
	return xxx_messageInfo_NodeConfig.Size(m)
}
func (m *NodeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_NodeConfig proto.InternalMessageInfo

func (m *NodeConfig) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NodeConfig) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *NodeConfig) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type GetNodeConfigsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeConfigsRequest) Reset()         { *m = GetNodeConfigsRequest{} }
func (m *GetNodeConfigsRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeConfigsRequest) ProtoMessage()    {}
func (*GetNodeConfigsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{19}
}
func (m *GetNodeConfigsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeConfigsRequest.Unmarshal(m, b)
}
func (m *GetNodeConfigsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeConfigsRequest.Marshal(b, m, deterministic)
}
func (dst *GetNodeConfigsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeConfigsRequest.Merge(dst, src)
}
func (m *GetNodeConfigsRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeConfigsRequest.Size(m)
}
func (m *GetNodeConfigsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeConfigsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeConfigsRequest proto.InternalMessageInfo

type GetNodeConfigsResponse struct {
	NodeConfigs          []*NodeConfig `protobuf:"bytes,1,rep,name=node_configs,json=nodeConfigs,proto3" json:"node_configs,omitempty" bson:"node_configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetNodeConfigsResponse) Reset()         { *m = GetNodeConfigsResponse{} }
func (m *GetNodeConfigsResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeConfigsResponse) ProtoMessage()    {}
func (*GetNodeConfigsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rulechain_98602d1cbc5949d3, []int{20}
}
func (m *GetNodeConfigsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeConfigsResponse.Unmarshal(m, b)
}
func (m *GetNodeConfigsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeConfigsResponse.Marshal(b, m, deterministic)
}
func (dst *GetNodeConfigsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeConfigsResponse.Merge(dst, src)
}
func (m *GetNodeConfigsResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeConfigsResponse.Size(m)
}
func (m *GetNodeConfigsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeConfigsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeConfigsResponse proto.InternalMessageInfo

func (m *GetNodeConfigsResponse) GetNodeConfigs() []*NodeConfig {
	if m != nil {
		return m.NodeConfigs
	}
	return nil
}

func init() {
	proto.RegisterType((*RuleChain)(nil), "grpc.rulechain.v1.RuleChain")
	proto.RegisterType((*CheckRuleChainRequest)(nil), "grpc.rulechain.v1.CheckRuleChainRequest")
	proto.RegisterType((*CheckRuleChainResponse)(nil), "grpc.rulechain.v1.CheckRuleChainResponse")
	proto.RegisterType((*CreateRuleChainRequest)(nil), "grpc.rulechain.v1.CreateRuleChainRequest")
	proto.RegisterType((*RuleChainConfig)(nil), "grpc.rulechain.v1.RuleChainConfig")
	proto.RegisterType((*CreateRuleChainResponse)(nil), "grpc.rulechain.v1.CreateRuleChainResponse")
	proto.RegisterType((*DeleteRuleChainRequest)(nil), "grpc.rulechain.v1.DeleteRuleChainRequest")
	proto.RegisterType((*DeleteRuleChainResponse)(nil), "grpc.rulechain.v1.DeleteRuleChainResponse")
	proto.RegisterType((*UpdateRuleChainRequest)(nil), "grpc.rulechain.v1.UpdateRuleChainRequest")
	proto.RegisterType((*UpdateRuleChainResponse)(nil), "grpc.rulechain.v1.UpdateRuleChainResponse")
	proto.RegisterType((*GetRuleChainRequest)(nil), "grpc.rulechain.v1.GetRuleChainRequest")
	proto.RegisterType((*GetRuleChainResponse)(nil), "grpc.rulechain.v1.GetRuleChainResponse")
	proto.RegisterType((*GetRuleChainsRequest)(nil), "grpc.rulechain.v1.GetRuleChainsRequest")
	proto.RegisterType((*GetRuleChainsResponse)(nil), "grpc.rulechain.v1.GetRuleChainsResponse")
	proto.RegisterType((*StartRuleChainRequest)(nil), "grpc.rulechain.v1.StartRuleChainRequest")
	proto.RegisterType((*StartRuleChainResponse)(nil), "grpc.rulechain.v1.StartRuleChainResponse")
	proto.RegisterType((*StopRuleChainRequest)(nil), "grpc.rulechain.v1.StopRuleChainRequest")
	proto.RegisterType((*StopRuleChainResponse)(nil), "grpc.rulechain.v1.StopRuleChainResponse")
	proto.RegisterType((*NodeConfig)(nil), "grpc.rulechain.v1.NodeConfig")
	proto.RegisterType((*GetNodeConfigsRequest)(nil), "grpc.rulechain.v1.GetNodeConfigsRequest")
	proto.RegisterType((*GetNodeConfigsResponse)(nil), "grpc.rulechain.v1.GetNodeConfigsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RuleChainServiceClient is the client API for RuleChainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RuleChainServiceClient interface {
	// RuleChain
	CheckRuleChain(ctx context.Context, in *CheckRuleChainRequest, opts ...grpc.CallOption) (*CheckRuleChainResponse, error)
	CreateRuleChain(ctx context.Context, in *CreateRuleChainRequest, opts ...grpc.CallOption) (*CreateRuleChainResponse, error)
	DeleteRuleChain(ctx context.Context, in *DeleteRuleChainRequest, opts ...grpc.CallOption) (*DeleteRuleChainResponse, error)
	UpdateRuleChain(ctx context.Context, in *UpdateRuleChainRequest, opts ...grpc.CallOption) (*UpdateRuleChainResponse, error)
	GetRuleChain(ctx context.Context, in *GetRuleChainRequest, opts ...grpc.CallOption) (*GetRuleChainResponse, error)
	GetRuleChains(ctx context.Context, in *GetRuleChainsRequest, opts ...grpc.CallOption) (*GetRuleChainsResponse, error)
	StartRuleChain(ctx context.Context, in *StartRuleChainRequest, opts ...grpc.CallOption) (*StartRuleChainResponse, error)
	StopRuleChain(ctx context.Context, in *StopRuleChainRequest, opts ...grpc.CallOption) (*StopRuleChainResponse, error)
	// RuleChain Node Configs
	GetNodeConfigs(ctx context.Context, in *GetNodeConfigsRequest, opts ...grpc.CallOption) (*GetNodeConfigsResponse, error)
}

type ruleChainServiceClient struct {
	cc *grpc.ClientConn
}

func NewRuleChainServiceClient(cc *grpc.ClientConn) RuleChainServiceClient {
	return &ruleChainServiceClient{cc}
}

func (c *ruleChainServiceClient) CheckRuleChain(ctx context.Context, in *CheckRuleChainRequest, opts ...grpc.CallOption) (*CheckRuleChainResponse, error) {
	out := new(CheckRuleChainResponse)
	err := c.cc.Invoke(ctx, "/grpc.rulechain.v1.RuleChainService/CheckRuleChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) CreateRuleChain(ctx context.Context, in *CreateRuleChainRequest, opts ...grpc.CallOption) (*CreateRuleChainResponse, error) {
	out := new(CreateRuleChainResponse)
	err := c.cc.Invoke(ctx, "/grpc.rulechain.v1.RuleChainService/CreateRuleChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) DeleteRuleChain(ctx context.Context, in *DeleteRuleChainRequest, opts ...grpc.CallOption) (*DeleteRuleChainResponse, error) {
	out := new(DeleteRuleChainResponse)
	err := c.cc.Invoke(ctx, "/grpc.rulechain.v1.RuleChainService/DeleteRuleChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) UpdateRuleChain(ctx context.Context, in *UpdateRuleChainRequest, opts ...grpc.CallOption) (*UpdateRuleChainResponse, error) {
	out := new(UpdateRuleChainResponse)
	err := c.cc.Invoke(ctx, "/grpc.rulechain.v1.RuleChainService/UpdateRuleChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) GetRuleChain(ctx context.Context, in *GetRuleChainRequest, opts ...grpc.CallOption) (*GetRuleChainResponse, error) {
	out := new(GetRuleChainResponse)
	err := c.cc.Invoke(ctx, "/grpc.rulechain.v1.RuleChainService/GetRuleChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) GetRuleChains(ctx context.Context, in *GetRuleChainsRequest, opts ...grpc.CallOption) (*GetRuleChainsResponse, error) {
	out := new(GetRuleChainsResponse)
	err := c.cc.Invoke(ctx, "/grpc.rulechain.v1.RuleChainService/GetRuleChains", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) StartRuleChain(ctx context.Context, in *StartRuleChainRequest, opts ...grpc.CallOption) (*StartRuleChainResponse, error) {
	out := new(StartRuleChainResponse)
	err := c.cc.Invoke(ctx, "/grpc.rulechain.v1.RuleChainService/StartRuleChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) StopRuleChain(ctx context.Context, in *StopRuleChainRequest, opts ...grpc.CallOption) (*StopRuleChainResponse, error) {
	out := new(StopRuleChainResponse)
	err := c.cc.Invoke(ctx, "/grpc.rulechain.v1.RuleChainService/StopRuleChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleChainServiceClient) GetNodeConfigs(ctx context.Context, in *GetNodeConfigsRequest, opts ...grpc.CallOption) (*GetNodeConfigsResponse, error) {
	out := new(GetNodeConfigsResponse)
	err := c.cc.Invoke(ctx, "/grpc.rulechain.v1.RuleChainService/GetNodeConfigs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleChainServiceServer is the server API for RuleChainService service.
type RuleChainServiceServer interface {
	// RuleChain
	CheckRuleChain(context.Context, *CheckRuleChainRequest) (*CheckRuleChainResponse, error)
	CreateRuleChain(context.Context, *CreateRuleChainRequest) (*CreateRuleChainResponse, error)
	DeleteRuleChain(context.Context, *DeleteRuleChainRequest) (*DeleteRuleChainResponse, error)
	UpdateRuleChain(context.Context, *UpdateRuleChainRequest) (*UpdateRuleChainResponse, error)
	GetRuleChain(context.Context, *GetRuleChainRequest) (*GetRuleChainResponse, error)
	GetRuleChains(context.Context, *GetRuleChainsRequest) (*GetRuleChainsResponse, error)
	StartRuleChain(context.Context, *StartRuleChainRequest) (*StartRuleChainResponse, error)
	StopRuleChain(context.Context, *StopRuleChainRequest) (*StopRuleChainResponse, error)
	// RuleChain Node Configs
	GetNodeConfigs(context.Context, *GetNodeConfigsRequest) (*GetNodeConfigsResponse, error)
}

func RegisterRuleChainServiceServer(s *grpc.Server, srv RuleChainServiceServer) {
	s.RegisterService(&_RuleChainService_serviceDesc, srv)
}

func _RuleChainService_CheckRuleChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRuleChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).CheckRuleChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.rulechain.v1.RuleChainService/CheckRuleChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).CheckRuleChain(ctx, req.(*CheckRuleChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_CreateRuleChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuleChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).CreateRuleChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.rulechain.v1.RuleChainService/CreateRuleChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).CreateRuleChain(ctx, req.(*CreateRuleChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_DeleteRuleChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuleChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).DeleteRuleChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.rulechain.v1.RuleChainService/DeleteRuleChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).DeleteRuleChain(ctx, req.(*DeleteRuleChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_UpdateRuleChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRuleChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).UpdateRuleChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.rulechain.v1.RuleChainService/UpdateRuleChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).UpdateRuleChain(ctx, req.(*UpdateRuleChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_GetRuleChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).GetRuleChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.rulechain.v1.RuleChainService/GetRuleChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).GetRuleChain(ctx, req.(*GetRuleChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_GetRuleChains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuleChainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).GetRuleChains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.rulechain.v1.RuleChainService/GetRuleChains",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).GetRuleChains(ctx, req.(*GetRuleChainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_StartRuleChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRuleChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).StartRuleChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.rulechain.v1.RuleChainService/StartRuleChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).StartRuleChain(ctx, req.(*StartRuleChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_StopRuleChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRuleChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).StopRuleChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.rulechain.v1.RuleChainService/StopRuleChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).StopRuleChain(ctx, req.(*StopRuleChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuleChainService_GetNodeConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleChainServiceServer).GetNodeConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.rulechain.v1.RuleChainService/GetNodeConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleChainServiceServer).GetNodeConfigs(ctx, req.(*GetNodeConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RuleChainService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.rulechain.v1.RuleChainService",
	HandlerType: (*RuleChainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckRuleChain",
			Handler:    _RuleChainService_CheckRuleChain_Handler,
		},
		{
			MethodName: "CreateRuleChain",
			Handler:    _RuleChainService_CreateRuleChain_Handler,
		},
		{
			MethodName: "DeleteRuleChain",
			Handler:    _RuleChainService_DeleteRuleChain_Handler,
		},
		{
			MethodName: "UpdateRuleChain",
			Handler:    _RuleChainService_UpdateRuleChain_Handler,
		},
		{
			MethodName: "GetRuleChain",
			Handler:    _RuleChainService_GetRuleChain_Handler,
		},
		{
			MethodName: "GetRuleChains",
			Handler:    _RuleChainService_GetRuleChains_Handler,
		},
		{
			MethodName: "StartRuleChain",
			Handler:    _RuleChainService_StartRuleChain_Handler,
		},
		{
			MethodName: "StopRuleChain",
			Handler:    _RuleChainService_StopRuleChain_Handler,
		},
		{
			MethodName: "GetNodeConfigs",
			Handler:    _RuleChainService_GetNodeConfigs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rulechain.proto",
}

func init() { proto.RegisterFile("rulechain.proto", fileDescriptor_rulechain_98602d1cbc5949d3) }

var fileDescriptor_rulechain_98602d1cbc5949d3 = []byte{
	// 714 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0xd3, 0x36, 0x6d, 0x26, 0xa1, 0x85, 0xa5, 0x75, 0x5c, 0x0b, 0xa4, 0xb0, 0x07, 0x08,
	0x1c, 0x22, 0xd1, 0xde, 0x8a, 0x90, 0x90, 0x12, 0xa9, 0x54, 0x42, 0x48, 0x38, 0x6d, 0x0f, 0x5c,
	0xaa, 0x25, 0x5e, 0xd2, 0x40, 0xea, 0x35, 0xf6, 0xa6, 0x52, 0x1e, 0x83, 0x87, 0xe0, 0x3d, 0x78,
	0x34, 0xe4, 0xdd, 0xf5, 0xcf, 0xda, 0x1b, 0x1c, 0x44, 0x6f, 0x3b, 0xe3, 0x99, 0xf9, 0xe6, 0xf7,
	0x93, 0x61, 0x3f, 0x5a, 0xcc, 0xe9, 0xe4, 0x86, 0xcc, 0x82, 0x41, 0x18, 0x31, 0xce, 0xd0, 0xa3,
	0x69, 0x14, 0x4e, 0x06, 0xb9, 0xf6, 0xee, 0x35, 0xfe, 0x65, 0x41, 0xcb, 0x5b, 0xcc, 0xe9, 0x30,
	0x51, 0x20, 0x04, 0x5b, 0x01, 0xb9, 0xa5, 0x8e, 0xd5, 0xb3, 0xfa, 0x2d, 0x4f, 0xbc, 0xd1, 0x1e,
	0x34, 0xce, 0x47, 0x4e, 0x43, 0x68, 0x1a, 0xe7, 0x23, 0x64, 0x43, 0x73, 0x11, 0xd3, 0xe8, 0x7c,
	0xe4, 0x6c, 0x0a, 0x9d, 0x92, 0x12, 0x5f, 0xbe, 0x0c, 0xa9, 0xb3, 0x25, 0x7d, 0x93, 0x77, 0x62,
	0xeb, 0xb3, 0x5b, 0x32, 0x0b, 0x9c, 0x6d, 0x69, 0x2b, 0x25, 0xe4, 0xc0, 0x4e, 0x48, 0x96, 0x73,
	0x46, 0x7c, 0xa7, 0xd9, 0xb3, 0xfa, 0x1d, 0x2f, 0x15, 0x13, 0x8f, 0x98, 0x13, 0xbe, 0x88, 0x9d,
	0x1d, 0xe9, 0x21, 0x25, 0x7c, 0x01, 0x87, 0xc3, 0x1b, 0x3a, 0xf9, 0x9e, 0xe5, 0xea, 0xd1, 0x1f,
	0x0b, 0x1a, 0x73, 0xf4, 0x06, 0x20, 0x29, 0xe8, 0x5a, 0x54, 0x24, 0x12, 0x6f, 0x1f, 0x3f, 0x19,
	0x54, 0x0a, 0x1d, 0xe4, 0x8e, 0xad, 0x28, 0x7d, 0xe2, 0xf7, 0x60, 0x97, 0xa3, 0xc6, 0x21, 0x0b,
	0x62, 0x8a, 0x0e, 0x60, 0xfb, 0x8e, 0xcc, 0x67, 0xbe, 0x88, 0xb8, 0xeb, 0x49, 0x21, 0xc9, 0x3b,
	0xa2, 0x24, 0x66, 0x41, 0xec, 0x34, 0x7a, 0x9b, 0xfd, 0x96, 0x97, 0x8a, 0xf8, 0xa7, 0x05, 0xf6,
	0x30, 0xa2, 0x84, 0xd3, 0x7b, 0xcd, 0x10, 0x9d, 0x42, 0x73, 0xc2, 0x82, 0xaf, 0xb3, 0xa9, 0x98,
	0x40, 0xfb, 0x18, 0xff, 0xcd, 0x71, 0x28, 0x2c, 0x3d, 0xe5, 0x81, 0xcf, 0x60, 0xbf, 0xf4, 0x09,
	0xf5, 0xa0, 0x4d, 0x03, 0x3f, 0x64, 0xb3, 0x80, 0x5f, 0x7a, 0x1f, 0xd4, 0x9c, 0x8b, 0xaa, 0x64,
	0x8c, 0x21, 0x8b, 0xb8, 0x1a, 0xb8, 0x78, 0xe3, 0x13, 0xe8, 0x56, 0x6a, 0x53, 0x7d, 0x2a, 0x74,
	0xc4, 0xd2, 0x3b, 0x12, 0x80, 0x3d, 0xa2, 0x73, 0x6a, 0x68, 0x48, 0xbe, 0x41, 0x96, 0xb6, 0x41,
	0x2e, 0xec, 0xca, 0xfd, 0xc8, 0xf6, 0x2d, 0x93, 0x93, 0xc4, 0xb3, 0xa6, 0x64, 0xab, 0x57, 0x54,
	0xe1, 0x23, 0xe8, 0x56, 0xf0, 0x64, 0x92, 0xf8, 0x02, 0xec, 0xcb, 0xd0, 0x37, 0xcd, 0xe6, 0x14,
	0xf2, 0x5e, 0xff, 0xeb, 0xf2, 0x1c, 0x41, 0xb7, 0x12, 0x55, 0x01, 0xde, 0xc0, 0xe3, 0x33, 0xca,
	0xd7, 0x2e, 0x3c, 0x3f, 0x93, 0x86, 0x76, 0x26, 0xcf, 0xa0, 0x93, 0x6f, 0x8e, 0xb9, 0xea, 0x31,
	0x1c, 0xe8, 0x48, 0x6a, 0x2e, 0xff, 0x75, 0x16, 0x03, 0x3d, 0x68, 0x5c, 0x93, 0x3f, 0xbe, 0x82,
	0xc3, 0x92, 0xbd, 0xca, 0xe2, 0xad, 0x9c, 0x9a, 0xcc, 0x42, 0x6e, 0x48, 0x5d, 0x1a, 0x90, 0xa5,
	0x11, 0x63, 0x0f, 0x0e, 0xc7, 0x9c, 0x44, 0xeb, 0x37, 0xb2, 0xdc, 0xb0, 0x46, 0xb5, 0x61, 0x0e,
	0xd8, 0xe5, 0x98, 0x6a, 0x68, 0x9f, 0xe0, 0x60, 0xcc, 0x59, 0x78, 0x9f, 0x60, 0xdd, 0xa4, 0x00,
	0x2d, 0xa4, 0xc2, 0xba, 0x02, 0xf8, 0xc8, 0x7c, 0xaa, 0xae, 0x32, 0xa5, 0x4e, 0xab, 0x40, 0x9d,
	0x2e, 0xec, 0x4e, 0x08, 0xa7, 0x53, 0x16, 0x2d, 0xd3, 0x63, 0x48, 0xe5, 0x22, 0x7d, 0x6e, 0x6a,
	0xf4, 0x99, 0x00, 0x9e, 0x51, 0x9e, 0x87, 0x4e, 0x47, 0x87, 0x3f, 0x83, 0x5d, 0xfe, 0xa0, 0x66,
	0xf4, 0x0e, 0x3a, 0x01, 0xf3, 0xe9, 0xb5, 0x24, 0x8d, 0x74, 0x48, 0x4f, 0x0d, 0x43, 0xca, 0xbd,
	0xbd, 0x76, 0x90, 0x47, 0x3a, 0xfe, 0xbd, 0x03, 0x0f, 0xb3, 0x12, 0xc7, 0x34, 0xba, 0x9b, 0x4d,
	0x28, 0x9a, 0xc2, 0x9e, 0x4e, 0xad, 0xa8, 0x6f, 0x08, 0x69, 0xe4, 0x74, 0xf7, 0xe5, 0x1a, 0x96,
	0xaa, 0x91, 0x1b, 0xe8, 0x1b, 0xec, 0x97, 0xc8, 0x09, 0x19, 0xfd, 0x8d, 0xe4, 0xec, 0xbe, 0x5a,
	0xc7, 0xb4, 0x88, 0x55, 0xe2, 0x18, 0x23, 0x96, 0x99, 0xf7, 0x8c, 0x58, 0xab, 0x28, 0x4b, 0x60,
	0x95, 0xe8, 0xc5, 0x88, 0x65, 0x26, 0x36, 0x23, 0xd6, 0x2a, 0xb6, 0xda, 0x40, 0x04, 0x3a, 0xc5,
	0x03, 0x46, 0xcf, 0x0d, 0xde, 0x06, 0x42, 0x73, 0x5f, 0xd4, 0xda, 0x65, 0x10, 0x3e, 0x3c, 0xd0,
	0x38, 0x02, 0xd5, 0xf9, 0xa6, 0xab, 0xeb, 0xf6, 0xeb, 0x0d, 0x33, 0x94, 0x29, 0xec, 0xe9, 0xd7,
	0x6d, 0xdc, 0x3a, 0x23, 0xa9, 0x18, 0xb7, 0x6e, 0x05, 0x55, 0x88, 0x72, 0xb4, 0xcb, 0x36, 0x96,
	0x63, 0xa2, 0x13, 0xb7, 0x5f, 0x6f, 0x58, 0x2c, 0x47, 0xbf, 0x5a, 0xb4, 0xa2, 0x19, 0xd5, 0x8b,
	0x37, 0x96, 0x63, 0xa6, 0x00, 0xbc, 0xf1, 0xa5, 0x29, 0x7e, 0x10, 0x4f, 0xfe, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xc5, 0x2a, 0xf7, 0x67, 0x33, 0x0a, 0x00, 0x00,
}
