// Code generated by go-swagger; DO NOT EDIT.

package rulechain

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/cloustone/pandas/models"
)

// SaveRuleChainHandlerFunc turns a function with the right signature into a save rule chain handler
type SaveRuleChainHandlerFunc func(SaveRuleChainParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn SaveRuleChainHandlerFunc) Handle(params SaveRuleChainParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// SaveRuleChainHandler interface for that can handle valid save rule chain params
type SaveRuleChainHandler interface {
	Handle(SaveRuleChainParams, *models.Principal) middleware.Responder
}

// NewSaveRuleChain creates a new http.Handler for the save rule chain operation
func NewSaveRuleChain(ctx *middleware.Context, handler SaveRuleChainHandler) *SaveRuleChain {
	return &SaveRuleChain{Context: ctx, Handler: handler}
}

/*SaveRuleChain swagger:route POST /rulechains/{ruleChainId} Rulechain saveRuleChain

save one rule chain

save one rule chain

*/
type SaveRuleChain struct {
	Context *middleware.Context
	Handler SaveRuleChainHandler
}

func (o *SaveRuleChain) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewSaveRuleChainParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
