// Code generated by go-swagger; DO NOT EDIT.

package rulechain

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SaveRuleChainMetadataOKCode is the HTTP code returned for type SaveRuleChainMetadataOK
const SaveRuleChainMetadataOKCode int = 200

/*SaveRuleChainMetadataOK excute successfully

swagger:response saveRuleChainMetadataOK
*/
type SaveRuleChainMetadataOK struct {
}

// NewSaveRuleChainMetadataOK creates SaveRuleChainMetadataOK with default headers values
func NewSaveRuleChainMetadataOK() *SaveRuleChainMetadataOK {

	return &SaveRuleChainMetadataOK{}
}

// WriteResponse to the client
func (o *SaveRuleChainMetadataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// SaveRuleChainMetadataBadRequestCode is the HTTP code returned for type SaveRuleChainMetadataBadRequest
const SaveRuleChainMetadataBadRequestCode int = 400

/*SaveRuleChainMetadataBadRequest Invalid metadata

swagger:response saveRuleChainMetadataBadRequest
*/
type SaveRuleChainMetadataBadRequest struct {
}

// NewSaveRuleChainMetadataBadRequest creates SaveRuleChainMetadataBadRequest with default headers values
func NewSaveRuleChainMetadataBadRequest() *SaveRuleChainMetadataBadRequest {

	return &SaveRuleChainMetadataBadRequest{}
}

// WriteResponse to the client
func (o *SaveRuleChainMetadataBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// SaveRuleChainMetadataNotFoundCode is the HTTP code returned for type SaveRuleChainMetadataNotFound
const SaveRuleChainMetadataNotFoundCode int = 404

/*SaveRuleChainMetadataNotFound rule chain not found

swagger:response saveRuleChainMetadataNotFound
*/
type SaveRuleChainMetadataNotFound struct {
}

// NewSaveRuleChainMetadataNotFound creates SaveRuleChainMetadataNotFound with default headers values
func NewSaveRuleChainMetadataNotFound() *SaveRuleChainMetadataNotFound {

	return &SaveRuleChainMetadataNotFound{}
}

// WriteResponse to the client
func (o *SaveRuleChainMetadataNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
