// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddProjectDeviceOKCode is the HTTP code returned for type AddProjectDeviceOK
const AddProjectDeviceOKCode int = 200

/*AddProjectDeviceOK successful operation

swagger:response addProjectDeviceOK
*/
type AddProjectDeviceOK struct {
}

// NewAddProjectDeviceOK creates AddProjectDeviceOK with default headers values
func NewAddProjectDeviceOK() *AddProjectDeviceOK {

	return &AddProjectDeviceOK{}
}

// WriteResponse to the client
func (o *AddProjectDeviceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// AddProjectDeviceBadRequestCode is the HTTP code returned for type AddProjectDeviceBadRequest
const AddProjectDeviceBadRequestCode int = 400

/*AddProjectDeviceBadRequest bad request

swagger:response addProjectDeviceBadRequest
*/
type AddProjectDeviceBadRequest struct {
}

// NewAddProjectDeviceBadRequest creates AddProjectDeviceBadRequest with default headers values
func NewAddProjectDeviceBadRequest() *AddProjectDeviceBadRequest {

	return &AddProjectDeviceBadRequest{}
}

// WriteResponse to the client
func (o *AddProjectDeviceBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddProjectDeviceNotFoundCode is the HTTP code returned for type AddProjectDeviceNotFound
const AddProjectDeviceNotFoundCode int = 404

/*AddProjectDeviceNotFound project not found

swagger:response addProjectDeviceNotFound
*/
type AddProjectDeviceNotFound struct {
}

// NewAddProjectDeviceNotFound creates AddProjectDeviceNotFound with default headers values
func NewAddProjectDeviceNotFound() *AddProjectDeviceNotFound {

	return &AddProjectDeviceNotFound{}
}

// WriteResponse to the client
func (o *AddProjectDeviceNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// AddProjectDeviceInternalServerErrorCode is the HTTP code returned for type AddProjectDeviceInternalServerError
const AddProjectDeviceInternalServerErrorCode int = 500

/*AddProjectDeviceInternalServerError server internal error

swagger:response addProjectDeviceInternalServerError
*/
type AddProjectDeviceInternalServerError struct {
}

// NewAddProjectDeviceInternalServerError creates AddProjectDeviceInternalServerError with default headers values
func NewAddProjectDeviceInternalServerError() *AddProjectDeviceInternalServerError {

	return &AddProjectDeviceInternalServerError{}
}

// WriteResponse to the client
func (o *AddProjectDeviceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
