// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cloustone/pandas/models"
)

// CreateProjectOKCode is the HTTP code returned for type CreateProjectOK
const CreateProjectOKCode int = 200

/*CreateProjectOK Successful operation

swagger:response createProjectOK
*/
type CreateProjectOK struct {

	/*
	  In: Body
	*/
	Payload *models.Project `json:"body,omitempty"`
}

// NewCreateProjectOK creates CreateProjectOK with default headers values
func NewCreateProjectOK() *CreateProjectOK {

	return &CreateProjectOK{}
}

// WithPayload adds the payload to the create project o k response
func (o *CreateProjectOK) WithPayload(payload *models.Project) *CreateProjectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create project o k response
func (o *CreateProjectOK) SetPayload(payload *models.Project) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateProjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateProjectBadRequestCode is the HTTP code returned for type CreateProjectBadRequest
const CreateProjectBadRequestCode int = 400

/*CreateProjectBadRequest Bad request

swagger:response createProjectBadRequest
*/
type CreateProjectBadRequest struct {
}

// NewCreateProjectBadRequest creates CreateProjectBadRequest with default headers values
func NewCreateProjectBadRequest() *CreateProjectBadRequest {

	return &CreateProjectBadRequest{}
}

// WriteResponse to the client
func (o *CreateProjectBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreateProjectInternalServerErrorCode is the HTTP code returned for type CreateProjectInternalServerError
const CreateProjectInternalServerErrorCode int = 500

/*CreateProjectInternalServerError Server internal error

swagger:response createProjectInternalServerError
*/
type CreateProjectInternalServerError struct {
}

// NewCreateProjectInternalServerError creates CreateProjectInternalServerError with default headers values
func NewCreateProjectInternalServerError() *CreateProjectInternalServerError {

	return &CreateProjectInternalServerError{}
}

// WriteResponse to the client
func (o *CreateProjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
