// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	"github.com/cloustone/pandas/models"
)

// GetProjectDeviceHandlerFunc turns a function with the right signature into a get project device handler
type GetProjectDeviceHandlerFunc func(GetProjectDeviceParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProjectDeviceHandlerFunc) Handle(params GetProjectDeviceParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetProjectDeviceHandler interface for that can handle valid get project device params
type GetProjectDeviceHandler interface {
	Handle(GetProjectDeviceParams, *models.Principal) middleware.Responder
}

// NewGetProjectDevice creates a new http.Handler for the get project device operation
func NewGetProjectDevice(ctx *middleware.Context, handler GetProjectDeviceHandler) *GetProjectDevice {
	return &GetProjectDevice{Context: ctx, Handler: handler}
}

/*GetProjectDevice swagger:route GET /project/{projectId}/devices/{deviceId} Project getProjectDevice

geet project's specified device

get project's specified device

*/
type GetProjectDevice struct {
	Context *middleware.Context
	Handler GetProjectDeviceHandler
}

func (o *GetProjectDevice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetProjectDeviceParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
