// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateProjectDeviceStatusOKCode is the HTTP code returned for type UpdateProjectDeviceStatusOK
const UpdateProjectDeviceStatusOKCode int = 200

/*UpdateProjectDeviceStatusOK successful operation

swagger:response updateProjectDeviceStatusOK
*/
type UpdateProjectDeviceStatusOK struct {
}

// NewUpdateProjectDeviceStatusOK creates UpdateProjectDeviceStatusOK with default headers values
func NewUpdateProjectDeviceStatusOK() *UpdateProjectDeviceStatusOK {

	return &UpdateProjectDeviceStatusOK{}
}

// WriteResponse to the client
func (o *UpdateProjectDeviceStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateProjectDeviceStatusBadRequestCode is the HTTP code returned for type UpdateProjectDeviceStatusBadRequest
const UpdateProjectDeviceStatusBadRequestCode int = 400

/*UpdateProjectDeviceStatusBadRequest Bad request

swagger:response updateProjectDeviceStatusBadRequest
*/
type UpdateProjectDeviceStatusBadRequest struct {
}

// NewUpdateProjectDeviceStatusBadRequest creates UpdateProjectDeviceStatusBadRequest with default headers values
func NewUpdateProjectDeviceStatusBadRequest() *UpdateProjectDeviceStatusBadRequest {

	return &UpdateProjectDeviceStatusBadRequest{}
}

// WriteResponse to the client
func (o *UpdateProjectDeviceStatusBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdateProjectDeviceStatusInternalServerErrorCode is the HTTP code returned for type UpdateProjectDeviceStatusInternalServerError
const UpdateProjectDeviceStatusInternalServerErrorCode int = 500

/*UpdateProjectDeviceStatusInternalServerError server internal error

swagger:response updateProjectDeviceStatusInternalServerError
*/
type UpdateProjectDeviceStatusInternalServerError struct {
}

// NewUpdateProjectDeviceStatusInternalServerError creates UpdateProjectDeviceStatusInternalServerError with default headers values
func NewUpdateProjectDeviceStatusInternalServerError() *UpdateProjectDeviceStatusInternalServerError {

	return &UpdateProjectDeviceStatusInternalServerError{}
}

// WriteResponse to the client
func (o *UpdateProjectDeviceStatusInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
