// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UpdateProjectOKCode is the HTTP code returned for type UpdateProjectOK
const UpdateProjectOKCode int = 200

/*UpdateProjectOK successfully operation

swagger:response updateProjectOK
*/
type UpdateProjectOK struct {
}

// NewUpdateProjectOK creates UpdateProjectOK with default headers values
func NewUpdateProjectOK() *UpdateProjectOK {

	return &UpdateProjectOK{}
}

// WriteResponse to the client
func (o *UpdateProjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// UpdateProjectNotFoundCode is the HTTP code returned for type UpdateProjectNotFound
const UpdateProjectNotFoundCode int = 404

/*UpdateProjectNotFound project not found

swagger:response updateProjectNotFound
*/
type UpdateProjectNotFound struct {
}

// NewUpdateProjectNotFound creates UpdateProjectNotFound with default headers values
func NewUpdateProjectNotFound() *UpdateProjectNotFound {

	return &UpdateProjectNotFound{}
}

// WriteResponse to the client
func (o *UpdateProjectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdateProjectInternalServerErrorCode is the HTTP code returned for type UpdateProjectInternalServerError
const UpdateProjectInternalServerErrorCode int = 500

/*UpdateProjectInternalServerError server internal error

swagger:response updateProjectInternalServerError
*/
type UpdateProjectInternalServerError struct {
}

// NewUpdateProjectInternalServerError creates UpdateProjectInternalServerError with default headers values
func NewUpdateProjectInternalServerError() *UpdateProjectInternalServerError {

	return &UpdateProjectInternalServerError{}
}

// WriteResponse to the client
func (o *UpdateProjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
