// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mixer.proto

package grpc_mixer_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateAgentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAgentRequest) Reset()         { *m = CreateAgentRequest{} }
func (m *CreateAgentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAgentRequest) ProtoMessage()    {}
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mixer_5023ce95a51d2f27, []int{0}
}
func (m *CreateAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAgentRequest.Unmarshal(m, b)
}
func (m *CreateAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAgentRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAgentRequest.Merge(dst, src)
}
func (m *CreateAgentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAgentRequest.Size(m)
}
func (m *CreateAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAgentRequest proto.InternalMessageInfo

type CreateAgentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAgentResponse) Reset()         { *m = CreateAgentResponse{} }
func (m *CreateAgentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAgentResponse) ProtoMessage()    {}
func (*CreateAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mixer_5023ce95a51d2f27, []int{1}
}
func (m *CreateAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAgentResponse.Unmarshal(m, b)
}
func (m *CreateAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAgentResponse.Marshal(b, m, deterministic)
}
func (dst *CreateAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAgentResponse.Merge(dst, src)
}
func (m *CreateAgentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAgentResponse.Size(m)
}
func (m *CreateAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAgentResponse proto.InternalMessageInfo

type DeleteAgentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAgentRequest) Reset()         { *m = DeleteAgentRequest{} }
func (m *DeleteAgentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAgentRequest) ProtoMessage()    {}
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mixer_5023ce95a51d2f27, []int{2}
}
func (m *DeleteAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAgentRequest.Unmarshal(m, b)
}
func (m *DeleteAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAgentRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAgentRequest.Merge(dst, src)
}
func (m *DeleteAgentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAgentRequest.Size(m)
}
func (m *DeleteAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAgentRequest proto.InternalMessageInfo

type DeleteAgentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAgentResponse) Reset()         { *m = DeleteAgentResponse{} }
func (m *DeleteAgentResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAgentResponse) ProtoMessage()    {}
func (*DeleteAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mixer_5023ce95a51d2f27, []int{3}
}
func (m *DeleteAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAgentResponse.Unmarshal(m, b)
}
func (m *DeleteAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAgentResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAgentResponse.Merge(dst, src)
}
func (m *DeleteAgentResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAgentResponse.Size(m)
}
func (m *DeleteAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAgentResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateAgentRequest)(nil), "grpc.mixer.v1.CreateAgentRequest")
	proto.RegisterType((*CreateAgentResponse)(nil), "grpc.mixer.v1.CreateAgentResponse")
	proto.RegisterType((*DeleteAgentRequest)(nil), "grpc.mixer.v1.DeleteAgentRequest")
	proto.RegisterType((*DeleteAgentResponse)(nil), "grpc.mixer.v1.DeleteAgentResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MixerClient is the client API for Mixer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MixerClient interface {
	CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*CreateAgentResponse, error)
	DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*DeleteAgentResponse, error)
}

type mixerClient struct {
	cc *grpc.ClientConn
}

func NewMixerClient(cc *grpc.ClientConn) MixerClient {
	return &mixerClient{cc}
}

func (c *mixerClient) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*CreateAgentResponse, error) {
	out := new(CreateAgentResponse)
	err := c.cc.Invoke(ctx, "/grpc.mixer.v1.Mixer/CreateAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mixerClient) DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*DeleteAgentResponse, error) {
	out := new(DeleteAgentResponse)
	err := c.cc.Invoke(ctx, "/grpc.mixer.v1.Mixer/DeleteAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MixerServer is the server API for Mixer service.
type MixerServer interface {
	CreateAgent(context.Context, *CreateAgentRequest) (*CreateAgentResponse, error)
	DeleteAgent(context.Context, *DeleteAgentRequest) (*DeleteAgentResponse, error)
}

func RegisterMixerServer(s *grpc.Server, srv MixerServer) {
	s.RegisterService(&_Mixer_serviceDesc, srv)
}

func _Mixer_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MixerServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.mixer.v1.Mixer/CreateAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MixerServer).CreateAgent(ctx, req.(*CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mixer_DeleteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MixerServer).DeleteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.mixer.v1.Mixer/DeleteAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MixerServer).DeleteAgent(ctx, req.(*DeleteAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mixer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.mixer.v1.Mixer",
	HandlerType: (*MixerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgent",
			Handler:    _Mixer_CreateAgent_Handler,
		},
		{
			MethodName: "DeleteAgent",
			Handler:    _Mixer_DeleteAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mixer.proto",
}

func init() { proto.RegisterFile("mixer.proto", fileDescriptor_mixer_5023ce95a51d2f27) }

var fileDescriptor_mixer_5023ce95a51d2f27 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcd, 0xac, 0x48,
	0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4d, 0x2f, 0x2a, 0x48, 0xd6, 0x83, 0x88,
	0x94, 0x19, 0x2a, 0x89, 0x70, 0x09, 0x39, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0x3a, 0xa6, 0xa7, 0xe6,
	0x95, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0x89, 0x72, 0x09, 0xa3, 0x88, 0x16, 0x17,
	0xe4, 0xe7, 0x15, 0xa7, 0x82, 0x14, 0xbb, 0xa4, 0xe6, 0xa4, 0x62, 0x2a, 0x46, 0x11, 0x85, 0x28,
	0x36, 0xda, 0xce, 0xc8, 0xc5, 0xea, 0x0b, 0xb2, 0x46, 0x28, 0x8c, 0x8b, 0x1b, 0xc9, 0x34, 0x21,
	0x45, 0x3d, 0x14, 0x27, 0xe8, 0x61, 0xda, 0x2f, 0xa5, 0x84, 0x4f, 0x09, 0xd4, 0x31, 0x0c, 0x20,
	0x73, 0x91, 0x2c, 0xc6, 0x30, 0x17, 0xd3, 0xa9, 0x18, 0xe6, 0x62, 0x71, 0xb7, 0x12, 0x43, 0x12,
	0x1b, 0x38, 0xa4, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xba, 0xac, 0xdf, 0x68, 0x38, 0x01,
	0x00, 0x00,
}
