// Code generated by go-swagger; DO NOT EDIT.

package dashboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/cloustone/pandas/models"
)

// GetDashboardReader is a Reader for the GetDashboard structure.
type GetDashboardReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDashboardReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDashboardOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetDashboardBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetDashboardInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDashboardOK creates a GetDashboardOK with default headers values
func NewGetDashboardOK() *GetDashboardOK {
	return &GetDashboardOK{}
}

/*GetDashboardOK handles this case with default header values.

Successful operation
*/
type GetDashboardOK struct {
	Payload *models.Dashboard
}

func (o *GetDashboardOK) Error() string {
	return fmt.Sprintf("[GET /dashboard][%d] getDashboardOK  %+v", 200, o.Payload)
}

func (o *GetDashboardOK) GetPayload() *models.Dashboard {
	return o.Payload
}

func (o *GetDashboardOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Dashboard)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDashboardBadRequest creates a GetDashboardBadRequest with default headers values
func NewGetDashboardBadRequest() *GetDashboardBadRequest {
	return &GetDashboardBadRequest{}
}

/*GetDashboardBadRequest handles this case with default header values.

Bad request
*/
type GetDashboardBadRequest struct {
}

func (o *GetDashboardBadRequest) Error() string {
	return fmt.Sprintf("[GET /dashboard][%d] getDashboardBadRequest ", 400)
}

func (o *GetDashboardBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDashboardInternalServerError creates a GetDashboardInternalServerError with default headers values
func NewGetDashboardInternalServerError() *GetDashboardInternalServerError {
	return &GetDashboardInternalServerError{}
}

/*GetDashboardInternalServerError handles this case with default header values.

Server internal error
*/
type GetDashboardInternalServerError struct {
}

func (o *GetDashboardInternalServerError) Error() string {
	return fmt.Sprintf("[GET /dashboard][%d] getDashboardInternalServerError ", 500)
}

func (o *GetDashboardInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
