// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LoginToken login token
// swagger:model LoginToken
type LoginToken struct {

	// access token
	AccessToken string `json:"access_token,omitempty"`

	// token type
	TokenType string `json:"token_type,omitempty"`
}

// Validate validates this login token
func (m *LoginToken) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LoginToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LoginToken) UnmarshalBinary(b []byte) error {
	var res LoginToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
